import { useState, useMemo } from "react";
import { useT } from "../theme/theme.js";
import { THEMES, SKIN_WAVE_GATE, SKIN_WAVE_3_GATE, SKIN_WAVE_4_GATE } from "../theme/theme.js";
import {
  STUDIO_MODULES, getModuleTypes, blotBorderStyle,
  BLOT_BORDERS, EFFECTS, SKIES, NAME_COLORS, REACTION_PACKS,
  AVATAR_ACCENTS, PAPERS, LILLOK_GEAR, FRAMES, REACTION_SETS,
} from "../constants.jsx";
import NameTag from "../NameTag.jsx";
import { FramedAvatar, ReactionIcon } from "../art.jsx";
import { renderAvatar } from "../engine/draw.jsx";

function ShopItem({owned,equipped,price,onClick,children,swatch}){const T=useT();return(<button onClick={onClick} className="lok-btn text-left rounded-2xl overflow-hidden w-full" style={{border:`3px solid ${equipped?T.accent:T.ink}`,background:T.card,boxShadow:`4px 4px 0 ${T.shadow}`}}>{swatch}<div className="px-2.5 py-2 flex items-center justify-between gap-2"><div className="min-w-0">{children}</div><span className="text-xs font-extrabold shrink-0" style={{color:equipped?T.alt:T.accent}}>{equipped?"On ✓":owned?"Equip":price===0?"Free":price}</span></div></button>);}

export default function Shop({loks,lokPass,kids,uiTheme,ownedThemes,effect,ownedEffects,sky,ownedSkies,modules=[],onBuyModule,cosmetics,owned,onBuyCosmetic,setKids,onBuyPass,onTheme,onEffect,onSky,founder=false,onFounderJoin,say,lokPassBusy=false}){
  const T=useT();const[catTab,setCatTab]=useState("featured");const[modTab,setModTab]=useState("layers");const[showAll,setShowAll]=useState(false);const[fHandle,setFHandle]=useState("");const[fEmail,setFEmail]=useState("");const[fBusy,setFBusy]=useState(false);
  const Section=({title,sub,children})=>(<section className="mt-5"><h3 className="lok-display text-base font-extrabold">{title}</h3>{sub&&<p className="text-xs opacity-60 mb-1">{sub}</p>}<div className="mt-2">{children}</div></section>);
  const has=(cat,id)=>owned[cat]?.includes(id);const eq=(cat,id)=>cosmetics[cat]===id;const buy=(cat,item)=>onBuyCosmetic(cat,item);
  const cats=[["featured","Featured"],["themes","Skins"],["effects","Effects"],["skies","Skies"],["cosmetic","Cosmetics"],["studio","Studio"],["paper","Paper"],["blot","Blot Shop"]];
  const moduleTypes=getModuleTypes();
  return(<div className="mt-4">
    <h2 className="lok-display text-lg font-extrabold">Shop</h2>
    <p className="text-sm opacity-70 mt-0.5">{kids?"Everything here is free play.":"Spend Loks you earn — or grab the LokPass."}</p>
    <div className="mt-3 flex gap-1.5 overflow-x-auto pb-1">{cats.map(([id,l])=>(<button key={id} onClick={()=>setCatTab(id)} className="lok-btn shrink-0 px-3 py-1.5 rounded-full text-sm font-bold" style={{border:`2.5px solid ${T.ink}`,background:catTab===id?T.ink:T.card,color:catTab===id?T.paper:T.ink}}>{l}</button>))}
      <button onClick={()=>setShowAll(s=>!s)} className="lok-btn shrink-0 px-3 py-1.5 rounded-full text-sm font-bold" style={{border:`2.5px solid ${showAll?T.accent:T.shadow}`,background:showAll?T.ink:T.card,color:showAll?T.paper:T.shadow}} aria-pressed={showAll}>👀 All items</button>
    </div>
    {catTab==="featured"&&(<>
      <div className="mt-3 p-4 rounded-2xl relative overflow-hidden" style={{border:`3px solid ${T.ink}`,background:T.ink,color:T.paper,boxShadow:`6px 6px 0 ${T.accent}`}}><div className="lok-display text-xl font-extrabold">Become a Founder 🏆</div><p className="text-sm opacity-85 mt-1">Back us on the alpha and get locked-in as a Lok founder. Your handle, preferences, and library snapshot are saved to our early-access server — founders get a permanent badge and priority access to beta.</p>{founder?<div className="mt-3 flex items-center gap-2 py-2.5"><span className="text-lg">✅</span><span className="lok-display font-extrabold">You're a Founder!</span></div>:<><div className="mt-3 flex gap-2"><input value={fHandle} onChange={e=>setFHandle(e.target.value)} placeholder="Your handle" className="lok-btn flex-1 px-3 py-2 rounded-xl text-sm font-bold" style={{background:T.paper,color:T.ink,border:`3px solid ${T.paper}`}}/><input value={fEmail} onChange={e=>setFEmail(e.target.value)} placeholder="Email (optional)" type="email" className="lok-btn flex-1 px-3 py-2 rounded-xl text-sm font-bold" style={{background:T.paper,color:T.ink,border:`3px solid ${T.paper}`}}/></div><button onClick={async()=>{if(!fHandle.trim()||fHandle.trim().length<2){say?.("Enter a handle");return;}setFBusy(true);try{await onFounderJoin?.(fHandle.trim(),fEmail.trim());say?.("You're a founder! Data secured on the test server 🏆","success");}catch{say?.("Couldn't reach the server — try again","error");}setFBusy(false);}} disabled={fBusy} className="lok-btn lok-display mt-3 w-full py-2.5 rounded-xl text-lg font-extrabold" style={{background:fBusy?T.alt:T.accent,color:T.onAccent,border:`3px solid ${T.paper}`,opacity:fBusy?0.7:1}}>{fBusy?"Sending…":"Secure Founder Status"}</button></>}</div>
      {!kids&&(<div className="mt-3 p-4 rounded-2xl relative overflow-hidden" style={{border:`3px solid ${T.ink}`,background:T.ink,color:T.paper,boxShadow:`6px 6px 0 ${T.accent}`}}><div className="lok-display text-xl font-extrabold">LokPass</div><p className="text-sm opacity-85 mt-1">No ads. Every UI theme unlocked. PASS badge.</p><button onClick={onBuyPass} disabled={lokPass||lokPassBusy} className="lok-btn lok-display mt-3 w-full py-2.5 rounded-xl text-lg font-extrabold" style={{background:lokPass||lokPassBusy?"transparent":T.accent,color:lokPass||lokPassBusy?T.paper:T.onAccent,border:`3px solid ${T.paper}`,opacity:lokPass?0.7:1}} aria-label={lokPass?"LokPass active":lokPassBusy?"Processing…":"Get LokPass"}>{lokPass?"Active ✓":lokPassBusy?"Processing…":"Get LokPass — $2.99"}</button></div>)}
      {!kids&&(<div className="mt-3 p-4 rounded-2xl relative overflow-hidden" style={{border:`3px solid ${T.ink}`,background:`linear-gradient(135deg, ${T.ink}, #4A3728)`,color:T.paper,boxShadow:`6px 6px 0 ${T.accent}`}}><div className="lok-display text-xl font-extrabold" style={{color:T.accent}}>🚀 Studio UBER</div><p className="text-sm opacity-85 mt-1">One purchase. Every brush, every tool, every layer pack, every feature. 37 modules for the price of 13. The ultimate creative kit.</p><button onClick={()=>{const uber=STUDIO_MODULES.find(m=>m.id==="module_uber");if(modules.includes("module_uber")){say("UBER already active — all modules unlocked");}else{onBuyModule(uber);}}} className="lok-btn lok-display mt-3 w-full py-2.5 rounded-xl text-lg font-extrabold" style={{background:modules.includes("module_uber")?"transparent":T.accent,color:modules.includes("module_uber")?T.paper:T.onAccent,border:`3px solid ${T.paper}`,opacity:modules.includes("module_uber")?0.7:1}} aria-label="Get Studio UBER">{modules.includes("module_uber")?"Active ✓":"Get Studio UBER — 999 Loks"}</button></div>)}
      <div className="mt-3 p-3 rounded-2xl flex items-center gap-3" style={{border:`3px solid ${T.ink}`,background:T.card}}><div className="flex-1"><div className="lok-display font-extrabold">Lok Juniors {kids?"· ON":""}</div><div className="text-xs opacity-70">Safe walled-garden mode for kids &amp; classrooms.</div></div><button onClick={()=>setKids(!kids)} className="lok-btn px-3 py-2 rounded-xl font-extrabold text-sm" style={{background:kids?T.alt:T.card,color:kids?"#fff":T.ink,border:`3px solid ${T.ink}`}} aria-pressed={kids}>{kids?"Turn off":"Turn on"}</button></div>
      {(()=>{
        const daySeed=Math.floor(Date.now()/86400000);
        const pick=(arr,off)=>arr[(daySeed+off)%arr.length];
        const themeEntries=Object.entries(THEMES);
        const todayTheme=themeEntries[(daySeed)%themeEntries.length];
        const todayEffect=pick(EFFECTS,1);
        const todayColor=pick(NAME_COLORS.filter(c=>c.id!=="default"),2);
        const todayPaper=pick(PAPERS.filter(p=>p.id!=="plain"),3);
        return(<Section title="✨ Today's picks" sub="New items featured daily. Grab them before they rotate!">
          <div className="grid grid-cols-2 gap-2">
            {themeEntries.length>0&&(()=>{const[id,th]=todayTheme;const own=ownedThemes.includes(id);const e2=uiTheme===id;return(<ShopItem key={"ft-"+id} owned={own} equipped={e2} price={th.price} onClick={()=>onTheme(id)}><div className="font-bold text-sm truncate">{th.name}</div><div className="text-[10px] opacity-70 truncate">Skin</div></ShopItem>);})()}
            {EFFECTS.length>0&&(()=>{const e=todayEffect;const own=ownedEffects.includes(e.id);const e2=effect===e.id;return(<ShopItem key={"fe-"+e.id} owned={own} equipped={e2} price={e.price} onClick={()=>onEffect(e.id,e)}><div className="font-bold text-sm truncate">{e.name}</div><div className="text-[10px] opacity-70 truncate">Effect</div></ShopItem>);})()}
            {NAME_COLORS.length>0&&(()=>{const c=todayColor;return(<ShopItem key={"fc-"+c.id} owned={has("nameColor",c.id)} equipped={eq("nameColor",c.id)} price={c.price} onClick={()=>buy("nameColor",c)}><div className="font-bold text-sm truncate" style={{color:c.color==="rainbow"?undefined:c.color||T.ink,background:c.color==="rainbow"?"linear-gradient(90deg,#FF5DA2,#E8B14B,#2FA9A0)":undefined,WebkitBackgroundClip:c.color==="rainbow"?"text":undefined,WebkitTextFillColor:c.color==="rainbow"?"transparent":undefined}}>{c.name}</div><div className="text-[10px] opacity-70 truncate">Name color</div></ShopItem>);})()}
            {PAPERS.length>0&&(()=>{const p=todayPaper;return(<ShopItem key={"fp-"+p.id} owned={has("paper",p.id)} equipped={eq("paper",p.id)} price={p.price} onClick={()=>buy("paper",p)}><div className="font-bold text-sm truncate">{p.name}</div><div className="text-[10px] opacity-70 truncate">Paper</div></ShopItem>);})()}
          </div>
        </Section>);
      })()}
    </>)}
    {catTab==="themes"&&!kids&&(<Section title="UI themes" sub={`Own skins to unlock new waves.`}><div className="grid grid-cols-2 gap-3">{Object.entries(THEMES).filter(([,th])=>showAll||(th.wave||1) < 2 || ownedThemes.length>=SKIN_WAVE_GATE).filter(([,th])=>showAll||(th.wave||1) < 3 || ownedThemes.length>=SKIN_WAVE_3_GATE).filter(([,th])=>showAll||(th.wave||1) < 4 || ownedThemes.length>=SKIN_WAVE_4_GATE).map(([id,th])=>{const own=ownedThemes.includes(id);const e2=uiTheme===id;return(<button key={id} onClick={()=>onTheme(id)} className="lok-btn text-left rounded-2xl overflow-hidden" style={{border:`3px solid ${e2?T.accent:own||showAll?T.ink:T.shadow}`,background:T.card,boxShadow:`4px 4px 0 ${T.shadow}`,opacity:own||showAll?1:.5}} aria-label={`Theme ${th.name}`}><div className="flex h-10 relative">{[th.paper,th.ink,th.accent,th.alt].map((c,k)=>(<div key={k} className="flex-1" style={{background:c}}/>))}{th.animated&&<><div className="absolute inset-0" style={{background:`linear-gradient(110deg, transparent 30%, ${th.accent}55 50%, transparent 70%)`,backgroundSize:"220% 100%",animation:"loksheen 2.8s linear infinite"}}/><span className="absolute top-1 right-1 lok-display px-1.5 rounded text-[9px] font-extrabold" style={{background:th.accent,color:th.onAccent}}>● LIVE</span></>}</div><div className="px-2.5 py-2"><div className="font-bold text-sm">{th.name}</div><div className="text-xs opacity-70">{th.desc}</div><div className="mt-1 text-xs font-extrabold" style={{color:T.accent}}>{e2?"Equipped":own?"Equip":showAll?lokPass?"In PASS":`${th.price} Loks`:"🔒 Wave "+(th.wave||1)}</div></div></button>);})}</div></Section>)}
    {catTab==="effects"&&(<Section title="Page effects"><div className="grid grid-cols-2 gap-2">{EFFECTS.map(e=>{const own=ownedEffects.includes(e.id);const e2=effect===e.id;return(<ShopItem key={e.id} owned={own} equipped={e2} price={e.price} onClick={()=>onEffect(e.id,e)}><div className="font-bold text-sm">{e.name}</div></ShopItem>);})}</div></Section>)}
    {catTab==="skies"&&(<Section title="Atmosphere"><div className="grid grid-cols-2 gap-2">{SKIES.map(s=>{const own=ownedSkies.includes(s.id);const e2=sky===s.id;return(<ShopItem key={s.id} owned={own} equipped={e2} price={s.price} onClick={()=>onSky(s.id,s)}><div className="font-bold text-sm">{s.name}</div></ShopItem>);})}</div></Section>)}
    {catTab==="cosmetic"&&(()=>{const sampleAvatar=renderAvatar(42);return(<>
      <Section title="Name color"><div className="grid grid-cols-2 gap-2">{NAME_COLORS.map(c=>(<ShopItem key={c.id} owned={has("nameColor",c.id)} equipped={eq("nameColor",c.id)} price={c.price} onClick={()=>buy("nameColor",c)}><NameTag name={c.name} color={c.id} className="font-bold text-sm" style={{color:T.ink}}/></ShopItem>))}</div></Section>
      <Section title="Reaction packs"><div className="grid grid-cols-2 gap-2">{REACTION_PACKS.map(r=>(<ShopItem key={r.id} owned={has("reactionPack",r.id)} equipped={eq("reactionPack",r.id)} price={r.price} onClick={()=>buy("reactionPack",r)} swatch={<div className="flex items-center justify-center gap-1.5 pt-2.5">{(REACTION_SETS[r.id]||[]).map(t2=><ReactionIcon key={t2} type={t2} size={22}/>)}</div>}><div className="font-bold text-sm leading-tight">{r.name}</div></ShopItem>))}</div></Section>
      <Section title="Avatar frames"><div className="grid grid-cols-2 gap-2">{FRAMES.map(f=>(<ShopItem key={f.id} owned={has("frame",f.id)} equipped={eq("frame",f.id)} price={f.price} onClick={()=>buy("frame",f)} swatch={<div className="flex items-center justify-center pt-3 pb-1"><FramedAvatar src={sampleAvatar} size={46} frame={f.id} ink={T.ink} acc={T.accent}/></div>}><div className="font-bold text-sm">{f.name}</div></ShopItem>))}</div></Section>
      <Section title="Avatar accents"><div className="grid grid-cols-2 gap-2">{AVATAR_ACCENTS.map(a=>(<ShopItem key={a.id} owned={has("avatarAccent",a.id)} equipped={eq("avatarAccent",a.id)} price={a.price} onClick={()=>buy("avatarAccent",a)} swatch={<div className="flex items-center justify-center pt-4 pb-1"><FramedAvatar src={sampleAvatar} size={44} accent={a.id} ink={T.ink} acc={T.accent}/></div>}><div className="font-bold text-sm">{a.name}</div></ShopItem>))}</div></Section>
    </>);})()}
    {catTab==="studio"&&(<>
      <div className="mt-3 flex gap-1.5 overflow-x-auto pb-1">{moduleTypes.filter(t=>t.type!=="achievement").map(({type,label})=>(<button key={type} onClick={()=>setModTab(type)} className="lok-btn shrink-0 px-3 py-1.5 rounded-full text-sm font-bold" style={{border:`2.5px solid ${T.ink}`,background:modTab===type?T.ink:T.card,color:modTab===type?T.paper:T.ink}}>{label}</button>))}</div>
      <Section title="Modules" sub="Purchase individually or earn through achievements.">
        <div className="grid grid-cols-2 gap-2">{moduleTypes.find(t=>t.type===modTab)?.items.map(m=>{const own=modules.includes(m.id);const isAchievement=m.type==="achievement";return(<ShopItem key={m.id} owned={own} equipped={own} price={isAchievement?0:m.price} onClick={()=>{if(isAchievement){say(`Unlockable: ${m.unlock}`);}else if(own){say(`Already owned: ${m.name}`);}else{onBuyModule?.(m);}}}><div className="font-bold text-sm">{m.name}</div><div className="text-[10px] opacity-70">{isAchievement?`🏅 ${m.unlock}`:m.desc}</div></ShopItem>);})}</div>
      </Section>
      <p className="mt-2 text-center text-xs opacity-60">Modules installed: {modules.length}/38 · {modules.filter(m=>STUDIO_MODULES.some(s=>s.id===m)).length} unique</p>
    </>)}
    {catTab==="paper"&&(<Section title="Canvas paper" sub="Paper textures and guides for your drawings."><div className="grid grid-cols-2 gap-2">{PAPERS.map(p=>(<ShopItem key={p.id} owned={has("paper",p.id)} equipped={eq("paper",p.id)} price={p.price} onClick={()=>buy("paper",p)}><div className="font-bold text-sm">{p.name}</div></ShopItem>))}</div></Section>)}
    {catTab==="blot"&&(<><Section title="Blot borders" sub="Borders for your LilLok container.">
      <div className="grid grid-cols-2 gap-2">{BLOT_BORDERS.map(b=>(
        <ShopItem key={b.id} owned={has("blotBorder",b.id)} equipped={eq("blotBorder",b.id)} price={b.price} onClick={()=>buy("blotBorder",b)}
          swatch={<div className="flex items-center justify-center py-3"><div className="rounded-full" style={{width:44,height:44,background:T.paper,...blotBorderStyle(b.id,T)}}/></div>}>
          <div className="font-bold text-sm">{b.name}</div>
        </ShopItem>))}
      </div>
    </Section>
    <Section title="LilLok gear" sub="Accessories for your ink buddy."><div className="grid grid-cols-2 gap-2">{LILLOK_GEAR.filter(g=>g.id!=="none").map(g=>(<ShopItem key={g.id} owned={has("lillokGear",g.id)} equipped={eq("lillokGear",g.id)} price={g.price} onClick={()=>buy("lillokGear",g)}><div className="font-bold text-sm">{g.name}</div></ShopItem>))}</div></Section></>)}
    <p className="mt-5 text-center text-xs opacity-60">Balance: {loks} Loks</p>
  </div>);
}
