import { useState } from "react";
import { useT, THEMES, SKIN_WAVE_GATE, SKIN_WAVE_3_GATE, SKIN_WAVE_4_GATE, blotBorderStyle } from "../theme/theme.js";
import {
  RARITY, EFFECTS, NAME_COLORS, PAPERS, MYTHIC_ITEMS, CELEBRATIONS, ANIMATION_FX, SKIES,
  CURSORS, FONT_PACKS, STICKER_PACKS, POST_EXPORTS, FRAMES, REACTION_PACKS, AVATAR_ACCENTS,
  STUDIO_MODULES, BLOT_BORDERS, LILLOK_GEAR, LILLOK_SKINS, LILLOK_AURAS, LILLOK_PETS,
  VOICE_PACKS, MUSIC_PACKS, getDailyRotation, getWeeklyRotation,
} from "../constants.jsx";
import MythicPreview from "../MythicPreview.jsx";

function ShopItem({owned,equipped,price,onClick,children,swatch,rarity}){const T=useT();const r=rarity&&RARITY[rarity];return(<button onClick={onClick} className={`lok-btn text-left rounded-2xl overflow-hidden w-full ${rarity?`rarity-${rarity}`:""}`} style={{border:`3px solid ${equipped?T.accent:r?.color||T.ink}`,background:T.card,boxShadow:r?.glow?`${r.glow}, 4px 4px 0 ${T.shadow}`:`4px 4px 0 ${T.shadow}`}}>{swatch}<div className="px-2.5 py-2 flex items-center justify-between gap-2"><div className="min-w-0">{children}</div><div className="flex items-center gap-1.5 shrink-0">{r&&!equipped&&!owned&&<span className="text-[9px] font-extrabold px-1.5 py-0.5 rounded-full" style={{background:r.color||T.ink,color:rarity==="mythic"?"#fff":T.paper}}>{r.icon}</span>}<span className="text-xs font-extrabold" style={{color:equipped?T.alt:T.accent}}>{equipped?"On ✓":owned?"Equip":price===0?"Free":price}</span></div></div></button>);}
export default function Shop({ccTier,say,modules=[],onBuyModule,loks,lokPass,kids,uiTheme,ownedThemes,effect,ownedEffects,sky,ownedSkies=[],onSky,animFx,ownedAnimFx=[],onAnimFx,fontPack,onFontPack,cursorPack,onCursorPack,musicPack,onMusicPack,stickerPack,onStickerPack,postExport,onPostExport,cosmetics,owned,onBuyCosmetic,setKids,onBuyPass,onTheme,onEffect,onCc,mythicOwned,mythicEquipped,onBuyMythic,dailyOwned,weeklyOwned,celebrationStyle,onCelebrationStyle}){
  const T=useT();const[catTab,setCatTab]=useState("featured");const[modTab,setModTab]=useState("layers");const[showAll,setShowAll]=useState(false);
  const Section=({title,sub,children})=>(<section className="mt-5"><h3 className="lok-display text-base font-extrabold">{title}</h3>{sub&&<p className="text-xs opacity-60 mb-1">{sub}</p>}<div className="mt-2">{children}</div></section>);
  const has=(cat,id)=>owned[cat]?.includes(id);const eq=(cat,id)=>cosmetics[cat]===id;const buy=(cat,item)=>onBuyCosmetic(cat,item);
  const cats=[["featured","Featured"],["themes","Skins"],["mythic","💎 Mythic"],["effects","Effects"],["fx","FX"],["skies","Skies"],["cosmetic","Cosmetics"],["studio","Studio"],["paper","Paper"],["cursors","Cursors"],["fonts","Fonts"],["stickers","Stickers"],["export","Export"],["blot","Blot Shop"],["lillok","LilLok+"],["music","Music"]];
  const moduleTypes=[{type:"layers",label:"Layers"},{type:"brush",label:"Brushes"},{type:"tool",label:"Tools"},{type:"feature",label:"Features"},{type:"canvas",label:"Canvas"}];
  return(<div className="mt-4">
    <h2 className="lok-display text-lg font-extrabold">Shop</h2>
    <p className="text-sm opacity-70 mt-0.5">{kids?"Everything here is free play.":"Spend Loks you earn — or grab the LokPass."}</p>
    <div className="mt-3 flex gap-1.5 overflow-x-auto pb-1">{cats.map(([id,l])=>(<button key={id} onClick={()=>setCatTab(id)} className="lok-btn shrink-0 px-3 py-1.5 rounded-full text-sm font-bold" style={{border:`2.5px solid ${T.ink}`,background:catTab===id?T.ink:T.card,color:catTab===id?T.paper:T.ink}}>{l}</button>))}
      <button onClick={()=>setShowAll(s=>!s)} className="lok-btn shrink-0 px-3 py-1.5 rounded-full text-sm font-bold" style={{border:`2.5px solid ${showAll?T.accent:T.shadow}`,background:showAll?T.ink:T.card,color:showAll?T.paper:T.shadow}} aria-pressed={showAll}>👀 All</button>
    </div>
    {catTab==="featured"&&(<>
      {!kids&&(<div className="mt-3 p-4 rounded-2xl relative overflow-hidden" style={{border:`3px solid ${T.ink}`,background:T.ink,color:T.paper,boxShadow:`6px 6px 0 ${T.accent}`}}><div className="lok-display text-xl font-extrabold">LokPass</div><p className="text-sm opacity-85 mt-1">No ads. Every UI theme unlocked. PASS badge.</p><button onClick={onBuyPass} disabled={lokPass} className="lok-btn lok-display mt-3 w-full py-2.5 rounded-xl text-lg font-extrabold" style={{background:lokPass?"transparent":T.accent,color:lokPass?T.paper:T.onAccent,border:`3px solid ${T.paper}`,opacity:lokPass?0.7:1}} aria-label={lokPass?"LokPass active":"Get LokPass"}>{lokPass?"Active ✓":"Get LokPass — $2.99"}</button></div>)}
      <div className="mt-3 p-3 rounded-2xl flex items-center gap-3" style={{border:`3px solid ${T.ink}`,background:T.card}}><div className="flex-1"><div className="lok-display font-extrabold">Lok Juniors {kids?"· ON":""}</div><div className="text-xs opacity-70">Safe walled-garden mode for kids &amp; classrooms.</div></div><button onClick={()=>setKids(!kids)} className="lok-btn px-3 py-2 rounded-xl font-extrabold text-sm" style={{background:kids?T.alt:T.card,color:kids?"#fff":T.ink,border:`3px solid ${T.ink}`}} aria-pressed={kids}>{kids?"Turn off":"Turn on"}</button></div>
      {(()=>{const dS=Math.floor(Date.now()/86400000);const wS=Math.floor(Date.now()/604800000);const pick=(a,o)=>a[(dS+o)%a.length];const tE=Object.entries(THEMES);const tT=tE[dS%tE.length];const tEf=pick(EFFECTS,1);const tC=pick(NAME_COLORS.filter(x=>x.id!=="default"),2);const tP=pick(PAPERS.filter(x=>x.id!=="plain"),3);const dailyItems=getDailyRotation();const weeklyItems=getWeeklyRotation();return(<>
        <Section title="✨ Today's picks" sub="New items featured daily!"><div className="grid grid-cols-2 gap-2">
          {tE.length>0&&(()=>{const[id,th]=tT;const own=ownedThemes.includes(id);const e2=uiTheme===id;return(<ShopItem key={"ft-"+id} owned={own} equipped={e2} price={th.price} onClick={()=>onTheme(id)}><div className="font-bold text-sm truncate">{th.name}</div><div className="text-[10px] opacity-70 truncate">Skin</div></ShopItem>);})()}
          {EFFECTS.length>0&&(()=>{const e=tEf;const own=ownedEffects.includes(e.id);const e2=effect===e.id;return(<ShopItem key={"fe-"+e.id} owned={own} equipped={e2} price={e.price} onClick={()=>onEffect(e.id,e)}><div className="font-bold text-sm truncate">{e.name}</div><div className="text-[10px] opacity-70 truncate">Effect</div></ShopItem>);})()}
          {NAME_COLORS.length>0&&(()=>{const c=tC;return(<ShopItem key={"fc-"+c.id} owned={has("nameColor",c.id)} equipped={eq("nameColor",c.id)} price={c.price} onClick={()=>buy("nameColor",c)}><div className="font-bold text-sm truncate" style={{color:c.color==="rainbow"?undefined:c.color||T.ink,background:c.color==="rainbow"?"linear-gradient(90deg,#FF5DA2,#E8B14B,#2FA9A0)":undefined,WebkitBackgroundClip:c.color==="rainbow"?"text":undefined,WebkitTextFillColor:c.color==="rainbow"?"transparent":undefined}}>{c.name}</div><div className="text-[10px] opacity-70 truncate">Name color</div></ShopItem>);})()}
          {PAPERS.length>0&&(()=>{const p=tP;const own=has("paper",p.id);const e2=eq("paper",p.id);return(<ShopItem key={"fp-"+p.id} owned={own} equipped={e2} price={p.price} onClick={()=>buy("paper",p)}><div className="font-bold text-sm truncate">{p.name}</div><div className="text-[10px] opacity-70 truncate">Paper</div></ShopItem>);})()}
        </div></Section>
        {weeklyItems.length>0&&<Section title="🗓️ This Week's Rotation" sub={`${weeklyItems.length} exclusive items — ${7-new Date().getDay()}d remaining!`}><div className="grid grid-cols-2 gap-2">{weeklyItems.map(item=>{const own=weeklyOwned?.includes(item.id);return(<ShopItem key={item.id} owned={own} rarity={item.rarity} price={item.price} onClick={()=>{if(!own)onBuyMythic?.(item,"weekly");}}><div className="font-bold text-sm truncate">{item.name}</div><div className="text-[10px] opacity-70 truncate">{item.desc}</div></ShopItem>);})}</div></Section>}
        {dailyItems.length>0&&<Section title="🌸 Today's Rotation" sub={`${dailyItems.length} daily deals — grab before they're gone!`}><div className="grid grid-cols-2 gap-2">{dailyItems.map(item=>{const own=dailyOwned?.includes(item.id);return(<ShopItem key={item.id} owned={own} rarity={item.rarity} price={item.price} onClick={()=>{if(!own)onBuyMythic?.(item,"daily");}}><div className="font-bold text-sm truncate">{item.name}</div><div className="text-[10px] opacity-70 truncate">{item.desc}</div></ShopItem>);})}</div></Section>}
      </>);})()}
    </>)}
    {catTab==="themes"&&!kids&&(<Section title="UI themes" sub={`Own skins to unlock new waves.`}><div className="grid grid-cols-2 gap-3">{Object.entries(THEMES).filter(([,th])=>showAll||(th.wave||1) < 2 || ownedThemes.length>=SKIN_WAVE_GATE).filter(([,th])=>showAll||(th.wave||1) < 3 || ownedThemes.length>=SKIN_WAVE_3_GATE).filter(([,th])=>showAll||(th.wave||1) < 4 || ownedThemes.length>=SKIN_WAVE_4_GATE).map(([id,th])=>{const own=ownedThemes.includes(id);const e2=uiTheme===id;return(<button key={id} onClick={()=>onTheme(id)} className="lok-btn text-left rounded-2xl overflow-hidden" style={{border:`3px solid ${e2?T.accent:own||showAll?T.ink:T.shadow}`,background:T.card,boxShadow:`4px 4px 0 ${T.shadow}`,opacity:own||showAll?1:.5}} aria-label={`Theme ${th.name}`}><div className="flex h-10 relative">{[th.paper,th.ink,th.accent,th.alt].map((c,k)=>(<div key={k} className="flex-1" style={{background:c}}/>))}{th.animated&&<><div className="absolute inset-0" style={{background:`linear-gradient(110deg, transparent 30%, ${th.accent}55 50%, transparent 70%)`,backgroundSize:"220% 100%",animation:"loksheen 2.8s linear infinite"}}/><span className="absolute top-1 right-1 lok-display px-1.5 rounded text-[9px] font-extrabold" style={{background:th.accent,color:th.onAccent}}>● LIVE</span></>}</div><div className="px-2.5 py-2"><div className="font-bold text-sm">{th.name}</div><div className="text-xs opacity-70">{th.desc}</div><div className="mt-1 text-xs font-extrabold" style={{color:T.accent}}>{e2?"Equipped":own?"Equip":showAll?lokPass?"In PASS":`${th.price} Loks`:"🔒 Wave "+(th.wave||1)}</div></div></button>);})}</div></Section>)}
    {catTab==="mythic"&&!kids&&(<><Section title="💎 Mythic Collection" sub="Legendary quality. GSAP-animated previews. The rarest items in LokBook."><div className="grid grid-cols-2 gap-3">{MYTHIC_ITEMS.map(item=>{const own=mythicOwned?.includes(item.id);const e2=mythicEquipped===item.id;return(<button key={item.id} onClick={()=>onBuyMythic?.(item)} className={`lok-btn text-left rounded-2xl overflow-hidden rarity-mythic ${e2?"":""}`} style={{border:`3px solid ${e2?T.accent:"transparent"}`,background:T.card,boxShadow:e2?`0 0 20px ${T.accent}`:`0 0 20px rgba(255,93,162,0.3)`,position:"relative"}}><div className="flex items-center justify-center py-3" style={{minHeight:100,background:`linear-gradient(135deg, ${T.paper}, ${T.card})`}}><MythicPreview itemId={item.fxId} rarity="mythic"/></div><div className="px-2.5 py-2 relative"><div className="font-bold text-sm truncate flex items-center gap-1">{item.name}{!own&&<span className="text-[8px] px-1 py-0.5 rounded-full rarity-mythic-badge">MYTHIC</span>}</div><div className="text-[10px] opacity-70 truncate">{item.desc}</div><div className="mt-1 text-xs font-extrabold" style={{color:e2?T.alt:T.accent}}>{e2?"Equipped":own?"Equip":`${item.price} Loks`}</div></div></button>);})}</div></Section>
      <Section title="🎉 Celebrations" sub="Event-only celebration styles — unbuyable. Click to equip."><div className="grid grid-cols-2 gap-3">{CELEBRATIONS.map(c=>{const e2=celebrationStyle===c.id;return(<button key={c.id} onClick={()=>{onCelebrationStyle?.(c.id);}} className="lok-btn text-left rounded-2xl overflow-hidden" style={{border:`3px solid ${e2?T.accent:T.ink}`,background:T.card,opacity:0.6,boxShadow:`4px 4px 0 ${T.shadow}`}}><div className="flex items-center justify-center py-6" style={{background:`linear-gradient(135deg, ${T.paper}, ${T.card})`}}><div className="text-3xl">{c.id==="confetti"?"🎊":c.id==="inkbloom"?"🌸":"✨"}</div></div><div className="px-2.5 py-2"><div className="font-bold text-sm">{c.name}</div><div className="text-[10px] opacity-70">{c.desc}</div><div className="mt-1 text-[9px] font-extrabold uppercase tracking-widest" style={{color:T.alt}}>EVENT ITEM — UNBUYABLE</div></div></button>);})}</div></Section></>)}
    {catTab==="effects"&&(<Section title="Page effects" sub="Background effects that play on your profile."><div className="grid grid-cols-2 gap-2">{EFFECTS.map(e=>{const own=ownedEffects.includes(e.id);const e2=effect===e.id;return(<ShopItem key={e.id} owned={own} equipped={e2} price={e.price} onClick={()=>onEffect(e.id,e)}><div className="font-bold text-sm">{e.name}</div><div className="text-[10px] opacity-70">Page effect</div></ShopItem>);})}</div></Section>)}
    {catTab==="fx"&&(<Section title="Animation FX" sub="Visual effects play over your flip when viewed."><div className="grid grid-cols-2 gap-2">{ANIMATION_FX.filter(f=>showAll||f.id!=="none").map(f=>{const own=ownedAnimFx.includes(f.id);const e2=animFx===f.id;return(<ShopItem key={f.id} owned={own} equipped={e2} price={f.price} onClick={()=>onAnimFx(f.id,f)}><div className="font-bold text-sm">{f.name}</div>{f.desc&&<div className="text-[10px] opacity-70">{f.desc}</div>}</ShopItem>);})}</div></Section>)}
    {catTab==="skies"&&(<Section title="Atmosphere" sub="Animated sky backgrounds behind your content."><div className="grid grid-cols-2 gap-2">{SKIES.map(s=>{const own=ownedSkies.includes(s.id);const e2=sky===s.id;return(<ShopItem key={s.id} owned={own} equipped={e2} price={s.price} onClick={()=>onSky(s.id,s)}><div className="font-bold text-sm">{s.name}</div><div className="text-[10px] opacity-70">Sky</div></ShopItem>);})}</div></Section>)}
    {catTab==="cursors"&&(<Section title="Drawing Cursors" sub="Custom cursor styles for the canvas."><div className="grid grid-cols-2 gap-2">{CURSORS.filter(c=>showAll||c.id!=="default").map(c=>{const own=has("cursorPack",c.id);const e2=eq("cursorPack",c.id);return(<ShopItem key={c.id} owned={own} equipped={e2} price={c.price} onClick={()=>buy("cursorPack",c)}><div className="font-bold text-sm">{c.name}</div><div className="text-[10px] opacity-70">Cursor</div></ShopItem>);})}</div></Section>)}
    {catTab==="fonts"&&(<Section title="Font Packs" sub="Change the app font style."><div className="grid grid-cols-2 gap-2">{FONT_PACKS.filter(f=>showAll||f.id!=="default").map(f=>{const own=has("fontPack",f.id);const e2=eq("fontPack",f.id);return(<ShopItem key={f.id} owned={own} equipped={e2} price={f.price} onClick={()=>buy("fontPack",f)}><div className="font-bold text-sm">{f.name}</div>{f.desc&&<div className="text-[10px] opacity-70">{f.desc}</div>}</ShopItem>);})}</div></Section>)}
    {catTab==="stickers"&&(<Section title="Sticker Packs" sub="Unlock themed sticker sets for your Studio."><div className="grid grid-cols-2 gap-2">{STICKER_PACKS.filter(s=>showAll||s.id!=="emoji").map(s=>{const own=has("stickerPack",s.id);const e2=eq("stickerPack",s.id);return(<ShopItem key={s.id} owned={own} equipped={e2} price={s.price} onClick={()=>buy("stickerPack",s)}><div className="font-bold text-sm">{s.name}</div><div className="text-[10px] opacity-70">{s.stickers.slice(0,4).join(" ")}{s.stickers.length>4?" +"+s.stickers.length:""}</div></ShopItem>);})}</div></Section>)}
    {catTab==="export"&&(<Section title="Export Formats" sub="Extra export options for your flips."><div className="grid grid-cols-2 gap-2">{POST_EXPORTS.filter(e=>showAll||e.id!=="png").map(e=>{const own=has("postExport",e.id);const e2=eq("postExport",e.id);return(<ShopItem key={e.id} owned={own} equipped={e2} price={e.price} onClick={()=>buy("postExport",e)}><div className="font-bold text-sm">{e.name}{e.soon&&<span className="ml-1 text-[9px] opacity-50">soon</span>}</div>{e.desc&&<div className="text-[10px] opacity-70">{e.desc}</div>}</ShopItem>);})}</div></Section>)}
    {catTab==="cosmetic"&&(<>
      <Section title="Name color"><div className="grid grid-cols-2 gap-2">{NAME_COLORS.map(c=>(<ShopItem key={c.id} owned={has("nameColor",c.id)} equipped={eq("nameColor",c.id)} price={c.price} onClick={()=>buy("nameColor",c)}><div className="font-bold text-sm" style={{color:c.color==="rainbow"?undefined:c.color||T.ink,background:c.color==="rainbow"?"linear-gradient(90deg,#FF5DA2,#E8B14B,#2FA9A0)":undefined,WebkitBackgroundClip:c.color==="rainbow"?"text":undefined,WebkitTextFillColor:c.color==="rainbow"?"transparent":undefined}}>{c.name}</div></ShopItem>))}</div></Section>
      <Section title="Avatar frames" sub="Decorative borders around your avatar."><div className="grid grid-cols-2 gap-2">{FRAMES.map(f=>{const own=has("frame",f.id);const e2=eq("frame",f.id);return(<ShopItem key={f.id} owned={own} equipped={e2} price={f.price} onClick={()=>buy("frame",f)}><div className="font-bold text-sm">{f.name}</div><div className="text-[10px] opacity-70">Avatar frame</div></ShopItem>);})}</div></Section>
      <Section title="Reaction packs" sub="Emoji/lok reaction sets for posts."><div className="grid grid-cols-2 gap-2">{REACTION_PACKS.map(r=>(<ShopItem key={r.id} owned={has("reactionPack",r.id)} equipped={eq("reactionPack",r.id)} price={r.price} onClick={()=>buy("reactionPack",r)}><div className="font-bold text-sm leading-tight">{r.name}</div><div className="text-[10px] opacity-70">Reaction set</div></ShopItem>))}</div></Section>
      <Section title="Avatar accents" sub="Small decorative elements on your avatar."><div className="grid grid-cols-2 gap-2">{AVATAR_ACCENTS.map(a=>(<ShopItem key={a.id} owned={has("avatarAccent",a.id)} equipped={eq("avatarAccent",a.id)} price={a.price} onClick={()=>buy("avatarAccent",a)}><div className="font-bold text-sm">{a.name}</div><div className="text-[10px] opacity-70">Avatar accent</div></ShopItem>))}</div></Section>
    </>)}
    {catTab==="studio"&&(<>
      <div className="mt-3 flex gap-1.5 overflow-x-auto pb-1">{moduleTypes.filter(t=>t.type!=="achievement").map(({type,label})=>(<button key={type} onClick={()=>setModTab(type)} className="lok-btn shrink-0 px-3 py-1.5 rounded-full text-sm font-bold" style={{border:`2.5px solid ${T.ink}`,background:modTab===type?T.ink:T.card,color:modTab===type?T.paper:T.ink}}>{label}</button>))}</div>
      <Section title="Modules" sub="Expand your studio toolbox."><div className="grid grid-cols-2 gap-2">{STUDIO_MODULES.filter(m=>m.type===modTab||modTab==="all").filter(m=>showAll||m.price>0).map(m=>{const own=modules.includes(m.id);return(<ShopItem key={m.id} owned={own} equipped={own} price={m.price} onClick={()=>{if(own){say("Already owned");}else if(m.price===0){say("Free — claim it!");onBuyModule?.(m);}else{onBuyModule?.(m);}}}><div className="font-bold text-sm">{m.name}</div>{m.desc&&<div className="text-[10px] opacity-70">{m.desc}</div>}</ShopItem>);})}</div></Section>
      {!modules.includes("module_uber")&&<Section title="Studio Pro" sub="Blend modes, symmetry (mirror · radial), fill, eyedropper, marker &amp; chalk brushes"><div className="flex items-center justify-between p-2.5 rounded-xl" style={{border:`3px solid ${T.ink}`,background:T.card}}><div className="font-bold text-sm">Pro easel unlock</div>{ccTier?<span className="text-sm font-extrabold" style={{color:T.alt}}>Owned ✓</span>:<button onClick={onCc} className="lok-btn px-3 py-1 rounded-full text-sm font-extrabold" style={{background:T.accent,color:T.onAccent,border:`2.5px solid ${T.ink}`}}>120 Loks</button>}</div></Section>}
    </>)}
    {catTab==="paper"&&(<Section title="Canvas paper" sub="Paper textures and drawing guides."><div className="grid grid-cols-2 gap-2">{PAPERS.map(p=>(<ShopItem key={p.id} owned={has("paper",p.id)} equipped={eq("paper",p.id)} price={p.price} onClick={()=>buy("paper",p)}><div className="font-bold text-sm">{p.name}</div><div className="text-[10px] opacity-70">Canvas texture</div></ShopItem>))}</div></Section>)}
    {catTab==="blot"&&(<><Section title="Blot borders" sub="Borders for your LilLok container.">
      <div className="grid grid-cols-2 gap-2">{BLOT_BORDERS.map(b=>(
        <ShopItem key={b.id} owned={has("blotBorder",b.id)} equipped={eq("blotBorder",b.id)} price={b.price} onClick={()=>buy("blotBorder",b)}
          swatch={<div className="flex items-center justify-center py-3"><div className="rounded-full" style={{width:44,height:44,background:T.paper,...blotBorderStyle(b.id,T)}}/></div>}>
          <div className="font-bold text-sm">{b.name}</div><div className="text-[10px] opacity-70">Blot border</div>
        </ShopItem>))}
      </div>
    </Section>
    <Section title="LilLok gear" sub="Accessories for your ink buddy."><div className="grid grid-cols-2 gap-2">{LILLOK_GEAR.filter(g=>g.id!=="none").map(g=>(<ShopItem key={g.id} owned={has("lillokGear",g.id)} equipped={eq("lillokGear",g.id)} price={g.price} onClick={()=>buy("lillokGear",g)}><div className="font-bold text-sm">{g.name}</div><div className="text-[10px] opacity-70">LilLok accessory</div></ShopItem>))}</div></Section></>)}
    {catTab==="lillok"&&(<>
      <Section title="LilLok Skins" sub="Change your LilLok's appearance."><div className="grid grid-cols-2 gap-2">{LILLOK_SKINS.filter(s=>s.id!=="none").map(s=>(<ShopItem key={s.id} owned={has("lillokSkin",s.id)} equipped={eq("lillokSkin",s.id)} price={s.price} onClick={()=>buy("lillokSkin",s)}><div className="font-bold text-sm">{s.name}</div><div className="text-[10px] opacity-70">LilLok skin</div></ShopItem>))}</div></Section>
      <Section title="LilLok Auras" sub="Glowing effects around your LilLok."><div className="grid grid-cols-2 gap-2">{LILLOK_AURAS.filter(a=>a.id!=="none").map(a=>(<ShopItem key={a.id} owned={has("lillokAura",a.id)} equipped={eq("lillokAura",a.id)} price={a.price} onClick={()=>buy("lillokAura",a)}><div className="font-bold text-sm">{a.name}</div><div className="text-[10px] opacity-70">Aura</div></ShopItem>))}</div></Section>
      <Section title="LilLok Pets" sub="Tiny companions that follow your LilLok."><div className="grid grid-cols-2 gap-2">{LILLOK_PETS.filter(p=>p.id!=="none").map(p=>(<ShopItem key={p.id} owned={has("lillokPet",p.id)} equipped={eq("lillokPet",p.id)} price={p.price} onClick={()=>buy("lillokPet",p)}><div className="font-bold text-sm">{p.name}</div><div className="text-[10px] opacity-70">Pet</div></ShopItem>))}</div></Section>
      <Section title="Voice Packs" sub="Voice styles for your LilLok."><div className="grid grid-cols-2 gap-2">{VOICE_PACKS.filter(v=>v.id!=="default").map(v=>(<ShopItem key={v.id} owned={has("voicePack",v.id)} equipped={eq("voicePack",v.id)} price={v.price} onClick={()=>buy("voicePack",v)}><div className="font-bold text-sm">{v.name}</div><div className="text-[10px] opacity-70">Voice pack</div></ShopItem>))}</div></Section>
    </>)}
    {catTab==="music"&&(<Section title="Background Music" sub="Ambient soundtracks for your studio sessions."><div className="grid grid-cols-2 gap-2">{MUSIC_PACKS.filter(m=>showAll||m.id!=="none").map(m=>{const own=has("musicPack",m.id);const e2=eq("musicPack",m.id);return(<ShopItem key={m.id} owned={own} equipped={e2} price={m.price} onClick={()=>buy("musicPack",m)}><div className="font-bold text-sm">{m.name}</div><div className="text-[10px] opacity-70">Music</div></ShopItem>);})}</div></Section>)}
    <p className="mt-5 text-center text-xs opacity-60">Balance: {loks} Loks</p>
  </div>);
}
