import { useState, useRef, forwardRef, useImperativeHandle, useEffect } from "react";
import { useT, ART } from "./theme/theme.js";
import { W, H, BLENDS, hasModule, getModuleLayers } from "./constants.jsx";
import { paperBase } from "./engine/draw.jsx";

const PALLETS={
  default:[ART.ink,ART.pink,ART.teal,"#E8B14B","#7A4FBF","#3E8E4B","#D94040","#5A5A5A","#FF8C42","#C4E8C2","#4EBFFF","#F7D4FF"],
  pastel:["#A8D8EA","#AA96DA","#FCBAD3","#FFFFD2","#B5EAD7","#FFDAC1","#E0BBE4","#FEC8D8","#D4F0F0","#FCE4EC","#E8D5B7","#C9E4DE"],
  neon:["#FF00FF","#00FFFF","#FFFF00","#00FF00","#FF6600","#FF0066","#00FF66","#6600FF","#FF3300","#33FF00","#0066FF","#FF0099"],
  earth:["#8B5A2B","#6B8E23","#556B2F","#A0522D","#CD853F","#8FBC8F","#BC8F8F","#BDB76B","#D2B48C","#9ACD32","#C4A882","#A89070"],
  ocean:["#006994","#00B4D8","#90E0EF","#CAF0F8","#03045E","#0077B6","#023E8A","#48CAE4","#ADE8F4","#023E8A","#0096C7","#00B4D8"],
  sunset:["#FF6B6B","#FF8E53","#FECA57","#48DBFB","#FF9FF3","#54A0FF","#FF9F43","#EE5A24","#F368E0","#0ABDE3","#FFC312","#C4E538"],
};

const DEMO_BRUSH_PRESETS=[
  {id:"starter",name:"Starter",flow:0.35,scatter:0.15,dabs:3,angleJitter:0.2,roundness:1},
  {id:"light",name:"Light Touch",flow:0.18,scatter:0.05,dabs:1,angleJitter:0.05,roundness:1},
  {id:"breezy",name:"Breezy",flow:0.25,scatter:0.5,dabs:5,angleJitter:0.6,roundness:0.6},
  {id:"featherweight",name:"Featherweight",flow:0.12,scatter:0.3,dabs:2,angleJitter:0.3,roundness:0.8},
  {id:"basics",name:"Bold Basics",flow:0.6,scatter:0.1,dabs:2,angleJitter:0.1,roundness:1},
];

const Easel=forwardRef(function Easel({modules=[],onionFrames=[],onStroke,paper="plain",legacyMode=false,onLegacyToggle},ref){
  const T=useT();const maxLayers=getModuleLayers(modules);
  const legacyRef=useRef(legacyMode);useEffect(()=>{legacyRef.current=legacyMode;},[legacyMode]);
  const hasMarker=hasModule(modules,"brush_marker");const hasChalk=hasModule(modules,"brush_chalk");const hasSym=hasModule(modules,"feat_symmetry");const hasCalligraphy=hasModule(modules,"brush_calligraphy");const hasNeon=hasModule(modules,"brush_neon");const hasSparkle=hasModule(modules,"brush_sparkle");const hasCrayon=hasModule(modules,"brush_crayon");const hasWash=hasModule(modules,"brush_wash");const hasGalaxy=hasModule(modules,"brush_galaxy");const showPro=hasMarker||hasChalk||hasSym||hasCalligraphy||hasNeon||hasSparkle||hasCrayon||hasWash||hasGalaxy;
  const brushList=[["ink","Ink"]];if(hasMarker)brushList.push(["marker","Marker"]);if(hasChalk)brushList.push(["chalk","Chalk"]);if(hasCalligraphy)brushList.push(["calligraphy","Cali"]);if(hasNeon)brushList.push(["neon","Neon"]);if(hasSparkle)brushList.push(["sparkle","Sprkl"]);if(hasCrayon)brushList.push(["crayon","Crayon"]);if(hasWash)brushList.push(["wash","Wash"]);if(hasGalaxy)brushList.push(["galaxy","Galxy"]);
  const hasTools=modules.some(m=>["tool_spray","tool_glow","tool_watercolor","tool_pattern","tool_shape","tool_gradient","tool_push","tool_smudge","tool_clone","tool_blur","tool_replace","tool_rulers","tool_transform"].includes(m));
  const[layers,setLayers]=useState([{id:1,visible:true,opacity:1,blend:"source-over"}]);
  const[active,setActive]=useState(1);const[tool,setTool]=useState("pen");const[color,setColor]=useState(ART.ink);  const[recentColors,setRecentColors]=useState(()=>{try{const r=localStorage.getItem("lok:recentColors");return r?JSON.parse(r):[];}catch{return[];}});const[size,setSize]=useState(7);const[symmetry,setSymmetry]=useState("none");const[brush,setBrush]=useState("ink");const[cursorPos,setCursorPos]=useState(null);const[zoom,setZoom]=useState(1);const[pan,setPan]=useState({x:0,y:0});const[clonePt,setClonePt]=useState(null);const[shapeMode,setShapeMode]=useState("rect");const[showGuides,setShowGuides]=useState(false);const[anchorPt,setAnchorPt]=useState(null);const[blurAmount,setBlurAmount]=useState(5);  const[refImg,setRefImg]=useState(null);const[refOpacity,setRefOpacity]=useState(0.3);const[smoothStrength,setSmoothStrength]=useState(0.5);const[palette,setPalette]=useState("default");const[canvasSize,setCanvasSize]=useState("default");const isPanning=useRef(false);const panStart=useRef({x:0,y:0});const pinchRef=useRef(null);
  const[dynamics,setDynamics]=useState(true);const[brushLabOpen,setBrushLabOpen]=useState(false);const[customBrushParams,setCustomBrushParams]=useState({flow:0.35,scatter:0.15,dabs:3,angleJitter:0.2,roundness:1});
  const hasBrushLabSave=hasModule(modules,"feat_brushlab_save");
  const[savedBrushes,setSavedBrushes]=useState(()=>{try{const r=localStorage.getItem("lok:customBrushes");return r?JSON.parse(r):[];}catch{return[];}});
  const lastMoveXY=useRef(null);const lastMoveT=useRef(0);const transformDrag=useRef(null);const labPreviewRef=useRef(null);
  const idRef=useRef(1);const canvases=useRef(new Map());const drawing=useRef(false);const undoStack=useRef([]);const redoStack=useRef([]);const wrapRef=useRef(null);const lastPts=useRef([]);const midPts=useRef([]);const activeLayer=layers.find(l=>l.id===active);
  const pointerRef=useRef({pressure:0.5,tiltX:0,tiltY:0,twist:0,pointerType:"mouse"});
  const toImg=cv=>cv.toDataURL("image/webp",0.72);
  useImperativeHandle(ref,()=>({
    composite(pageNum=null){const tmp=document.createElement("canvas");tmp.width=W;tmp.height=H;const ctx=tmp.getContext("2d");paperBase(ctx,pageNum);layers.forEach(l=>{const cv=canvases.current.get(l.id);if(cv&&l.visible){ctx.globalAlpha=l.opacity;ctx.globalCompositeOperation=l.blend;ctx.drawImage(cv,0,0);}});ctx.globalAlpha=1;ctx.globalCompositeOperation="source-over";return toImg(tmp);},
    blankFrame(){const tmp=document.createElement("canvas");tmp.width=W;tmp.height=H;paperBase(tmp.getContext("2d"),null);return toImg(tmp);},
    clearAll(){layers.forEach(l=>{const cv=canvases.current.get(l.id);if(cv)cv.getContext("2d").clearRect(0,0,W,H);});undoStack.current=[];redoStack.current=[];},
    async restoreFromImage(dataUrl){if(!dataUrl)return;const cv=canvases.current.get(layers[0].id);if(!cv)return;const img=new Image();await new Promise(res=>{img.onload=res;img.onerror=res;img.src=dataUrl;});cv.getContext("2d",{willReadFrequently:true}).drawImage(img,0,0,W,H);},
  }));
  const pos=e=>{const r=wrapRef.current.getBoundingClientRect();const vx=e.clientX-r.left,vy=e.clientY-r.top;return[(vx-pan.x)*W/(r.width*zoom),(vy-pan.y)*H/(r.height*zoom)];};
  const pushUndo=()=>{const cv=canvases.current.get(active);if(!cv)return;if(undoStack.current.length>29)undoStack.current.shift();undoStack.current.push({id:active,snap:cv.getContext("2d").getImageData(0,0,W,H)});redoStack.current=[];};
  const pct=n=>pointerRef.current;const effectiveSize=(pOff=1)=>{const p=pct().pressure;return size*(0.3+p*0.7)*pOff;};
  const dynMul=(e,cx,cy)=>{if(!dynamics)return 1;if(e.pointerType==="pen"&&typeof e.pressure==="number"&&e.pressure>0)return 0.4+Math.min(e.pressure,1)*0.9;const now=e.timeStamp||performance.now();let mul=1;if(lastMoveXY.current){const dt=Math.max(now-lastMoveT.current,1);const dist=Math.hypot(cx-lastMoveXY.current[0],cy-lastMoveXY.current[1]);const speed=dist/dt;mul=Math.max(0.55,Math.min(1.2,1.2-speed*2.4));}lastMoveT.current=now;lastMoveXY.current=[cx,cy];return mul;};
  const applyTransform=fn=>{const cv=canvases.current.get(active);if(!cv)return;pushUndo();const ctx=cv.getContext("2d");const snap=ctx.getImageData(0,0,W,H);const tmp=document.createElement("canvas");tmp.width=W;tmp.height=H;tmp.getContext("2d").putImageData(snap,0,0);ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(W/2,H/2);fn(ctx);ctx.drawImage(tmp,-W/2,-H/2);ctx.restore();};
  const rotateLayer=deg=>applyTransform(c=>c.rotate(deg*Math.PI/180));
  const scaleLayer=s=>applyTransform(c=>c.scale(s,s));
  const flipLayer=axis=>applyTransform(c=>c.scale(axis==="h"?-1:1,axis==="v"?-1:1));
  const commitTranslate=(dx,dy)=>applyTransform(c=>c.translate(dx,dy));
  const dabCustom=(ctx,x,y,sz,col,p)=>{const dots=Math.round(p.dabs);for(let d=0;d<dots;d++){const ox=(Math.random()-.5)*p.scatter*sz*1.6;const oy=(Math.random()-.5)*p.scatter*sz*1.6;ctx.globalAlpha=p.flow;ctx.fillStyle=col;ctx.save();ctx.translate(x+ox,y+oy);ctx.rotate((Math.random()-.5)*p.angleJitter*Math.PI);ctx.scale(1,Math.max(0.2,p.roundness));ctx.beginPath();ctx.arc(0,0,sz*0.5,0,Math.PI*2);ctx.fill();ctx.restore();}ctx.globalAlpha=1;};
  const customAt=(ctx,x,y)=>dabCustom(ctx,x,y,size,color,customBrushParams);
  const applyBrushPreset=p=>setCustomBrushParams({flow:p.flow,scatter:p.scatter,dabs:p.dabs,angleJitter:p.angleJitter,roundness:p.roundness});
  const useCustomBrush=()=>{setBrush("custom");if(tool==="eraser"||tool==="fill"||tool==="eyedrop")setTool("pen");};
  const saveBrushPreset=()=>{if(!hasBrushLabSave)return;const name=`Brush ${savedBrushes.length+1}`;const next=[...savedBrushes,{id:`custom_${Date.now()}`,name,...customBrushParams}];setSavedBrushes(next);try{localStorage.setItem("lok:customBrushes",JSON.stringify(next));}catch{}};
  useEffect(()=>{const cv=labPreviewRef.current;if(!cv||!brushLabOpen)return;const ctx=cv.getContext("2d");ctx.clearRect(0,0,cv.width,cv.height);for(let x=8;x<cv.width-8;x+=3){const y=cv.height/2+Math.sin(x*0.15)*cv.height*0.22;dabCustom(ctx,x,y,size*0.6,color,customBrushParams);}},[brushLabOpen,customBrushParams,size,color]);
  const legacyDabAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";ctx.globalAlpha=brush==="chalk"?0.5:0.09;ctx.fillStyle=color;const dots=brush==="chalk"?6:1;for(let d=0;d<dots;d++){const ox=brush==="chalk"?(Math.random()-.5)*size*1.4:0,oy=brush==="chalk"?(Math.random()-.5)*size*1.4:0;ctx.beginPath();ctx.arc(x+ox,y+oy,tool==="soft"?size*1.8:size*0.5,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const improvedDabAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;if(brush==="chalk"){const n=8+Math.round(pr*7);for(let d=0;d<n;d++){ctx.globalAlpha=0.3+Math.random()*0.4;const ox=(Math.random()-.5)*es*1.6,oy=(Math.random()-.5)*es*1.6;ctx.beginPath();ctx.arc(x+ox,y+oy,es*(0.3+Math.random()*0.5),0,Math.PI*2);ctx.fill();}}else if(tool==="soft"){const n=3+Math.round(pr*5);for(let d=0;d<n;d++){ctx.globalAlpha=0.05+pr*0.1;const a=Math.random()*Math.PI*2,r=Math.random()*es*1.6;ctx.beginPath();ctx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,es*0.8,0,Math.PI*2);ctx.fill();}}else{ctx.globalAlpha=0.6+pr*0.4;const j=(1-pr)*es*0.15;ctx.beginPath();ctx.arc(x+(Math.random()-.5)*j,y+(Math.random()-.5)*j,es*0.5,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const dabAt=(ctx,x,y)=>legacyRef.current?legacyDabAt(ctx,x,y):improvedDabAt(ctx,x,y);
  const legacySprayAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;const n=20+Math.round(size*3);for(let d=0;d<n;d++){const a=Math.random()*Math.PI*2,r=Math.random()*size;ctx.globalAlpha=0.12+Math.random()*0.15;ctx.beginPath();ctx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,size*0.3+Math.random()*size*0.4,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const improvedSprayAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);const tiltX=p.tiltX||0;ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;const n=30+Math.round(es*4);for(let d=0;d<n;d++){const a=Math.random()*Math.PI*2;const off=tiltX/90;const r=Math.random()*es*(1+Math.abs(off)*0.5);ctx.globalAlpha=0.08+Math.random()*0.12*pr;const dr=es*(0.2+Math.random()*0.5*(1-Math.abs(off)));ctx.beginPath();ctx.arc(x+Math.cos(a+off)*r*0.8,y+Math.sin(a+off)*r*0.8,dr,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const sprayAt=(ctx,x,y)=>legacyRef.current?legacySprayAt(ctx,x,y):improvedSprayAt(ctx,x,y);
  const legacyGlowAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";const g=ctx.createRadialGradient(x,y,0,x,y,size*2);g.addColorStop(0,color);g.addColorStop(0.3,color);g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.globalAlpha=0.35;ctx.beginPath();ctx.arc(x,y,size*2,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const improvedGlowAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);const flicker=0.85+Math.random()*0.15;ctx.globalCompositeOperation="source-over";const g=ctx.createRadialGradient(x,y,0,x,y,es*2.5);g.addColorStop(0,color);g.addColorStop(0.15,color);g.addColorStop(0.5,color+"88");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.globalAlpha=0.25*flicker*pr;ctx.beginPath();ctx.arc(x,y,es*2.5,0,Math.PI*2);ctx.fill();ctx.globalAlpha=0.4*flicker*pr;ctx.beginPath();ctx.arc(x,y,es*1.2,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const glowAt=(ctx,x,y)=>legacyRef.current?legacyGlowAt(ctx,x,y):improvedGlowAt(ctx,x,y);
  const legacyWatercolorAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";ctx.globalAlpha=0.12+Math.random()*0.15;ctx.fillStyle=color;const r=size*0.6+Math.random()*size*0.8;ctx.beginPath();ctx.arc(x+Math.random()*4-2,y+Math.random()*4-2,r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const improvedWatercolorAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);ctx.globalCompositeOperation="source-over";const blooms=3+Math.round(pr*2);for(let b=0;b<blooms;b++){ctx.globalAlpha=0.06+Math.random()*0.1*pr;ctx.fillStyle=color;const r=es*(0.4+Math.random()*0.8);const ox=Math.random()*8-4+(b-1)*2,oy=Math.random()*8-4+(b-1)*2;ctx.beginPath();ctx.arc(x+ox,y+oy,r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const watercolorAt=(ctx,x,y)=>legacyRef.current?legacyWatercolorAt(ctx,x,y):improvedWatercolorAt(ctx,x,y);
  const legacyCalligraphyAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";const w=size*(0.5+Math.sin(y*0.05)*0.5);ctx.fillStyle=color;ctx.globalAlpha=0.85;ctx.beginPath();ctx.ellipse(x,y,w/2,size*0.4,Math.sin(y*0.03)*0.3,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const improvedCalligraphyAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const tw=p.twist||0;const es=size*(0.3+pr*0.7);const twistAngle=tw*Math.PI/180;ctx.globalCompositeOperation="source-over";const w=es*(0.4+Math.sin(y*0.05+twistAngle)*0.6);ctx.fillStyle=color;ctx.globalAlpha=0.6+pr*0.35;ctx.beginPath();ctx.ellipse(x,y,w/2,es*0.35,twistAngle,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const calligraphyAt=(ctx,x,y)=>legacyRef.current?legacyCalligraphyAt(ctx,x,y):improvedCalligraphyAt(ctx,x,y);
  const legacyNeonAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";const g=ctx.createRadialGradient(x,y,0,x,y,size*1.8);g.addColorStop(0,color);g.addColorStop(0.2,"#fff");g.addColorStop(0.5,color);g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.globalAlpha=0.45;ctx.beginPath();ctx.arc(x,y,size*1.8,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const improvedNeonAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);const pulse=0.9+Math.random()*0.1;ctx.globalCompositeOperation="source-over";const g=ctx.createRadialGradient(x,y,0,x,y,es*2.2);g.addColorStop(0,color);g.addColorStop(0.15,"#fff");g.addColorStop(0.35,color);g.addColorStop(0.7,color+"66");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.globalAlpha=0.35*pulse*pr;ctx.beginPath();ctx.arc(x,y,es*2.2,0,Math.PI*2);ctx.fill();ctx.globalAlpha=0.6*pulse*pr;ctx.beginPath();ctx.arc(x,y,es*0.5,0,Math.PI*2);ctx.fillStyle="#fff";ctx.fill();ctx.globalAlpha=1;};
  const neonAt=(ctx,x,y)=>legacyRef.current?legacyNeonAt(ctx,x,y):improvedNeonAt(ctx,x,y);
  const legacySparkleAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;ctx.globalAlpha=0.9;const n=5+Math.round(Math.random()*4);for(let d=0;d<n;d++){const a=Math.random()*Math.PI*2,r=Math.random()*size*0.6;ctx.beginPath();ctx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,1+Math.random()*1.5,0,Math.PI*2);ctx.fill();}ctx.beginPath();ctx.arc(x,y,size*0.3,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x-1,y-1,size*0.12,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const improvedSparkleAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;const n=10+Math.round(pr*10);for(let d=0;d<n;d++){ctx.globalAlpha=0.4+Math.random()*0.5;const a=Math.random()*Math.PI*2,r=Math.random()*es*0.8;const sd=0.5+Math.random()*2;ctx.beginPath();ctx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,sd,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=0.95;ctx.beginPath();ctx.arc(x,y,es*0.35,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.globalAlpha=0.9;for(let d=0;d<4;d++){const sa=d*Math.PI/2;ctx.beginPath();ctx.arc(x+Math.cos(sa)*es*0.4,y+Math.sin(sa)*es*0.4,es*0.08,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const sparkleAt=(ctx,x,y)=>legacyRef.current?legacySparkleAt(ctx,x,y):improvedSparkleAt(ctx,x,y);
  const legacyCrayonAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";ctx.globalAlpha=0.7+Math.random()*0.25;ctx.fillStyle=color;const ox=(Math.random()-0.5)*size*0.4,oy=(Math.random()-0.5)*size*0.4;const r=size*0.5+Math.random()*size*0.3;ctx.beginPath();ctx.arc(x+ox,y+oy,r,0,Math.PI*2);ctx.fill();for(let d=0;d<3;d++){ctx.fillStyle=color;ctx.globalAlpha=0.15+Math.random()*0.2;ctx.beginPath();ctx.arc(x+(Math.random()-0.5)*size*0.6,y+(Math.random()-0.5)*size*0.6,size*0.2+Math.random()*size*0.3,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const improvedCrayonAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;ctx.globalAlpha=0.5+pr*0.4;const ox=(Math.random()-0.5)*es*0.35,oy=(Math.random()-0.5)*es*0.35;ctx.beginPath();ctx.arc(x+ox,y+oy,es*0.4+Math.random()*es*0.3,0,Math.PI*2);ctx.fill();const n=4+Math.round(pr*4);for(let d=0;d<n;d++){ctx.fillStyle=color;ctx.globalAlpha=0.1+Math.random()*0.2*pr;ctx.beginPath();ctx.arc(x+(Math.random()-0.5)*es*0.7,y+(Math.random()-0.5)*es*0.7,es*0.15+Math.random()*es*0.25,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;};
  const crayonAt=(ctx,x,y)=>legacyRef.current?legacyCrayonAt(ctx,x,y):improvedCrayonAt(ctx,x,y);
  const legacyWashAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";ctx.globalAlpha=0.06+Math.random()*0.1;ctx.fillStyle=color;const r=size*0.8+Math.random()*size*0.6;ctx.beginPath();ctx.arc(x+Math.random()*6-3,y+Math.random()*6-3,r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const improvedWashAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);ctx.globalCompositeOperation="source-over";const n=2+Math.round(pr*2);for(let w=0;w<n;w++){ctx.globalAlpha=0.04+Math.random()*0.06*pr;ctx.fillStyle=color;const r=es*(0.6+Math.random()*0.6);const ox=Math.random()*8-4,oy=Math.random()*8-4;ctx.beginPath();ctx.arc(x+ox,y+oy,r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=0.07*pr;const er=es*1.2;ctx.beginPath();ctx.arc(x,y,er,0,Math.PI*2);ctx.fillStyle=color+"33";ctx.fill();ctx.globalAlpha=1;};
  const washAt=(ctx,x,y)=>legacyRef.current?legacyWashAt(ctx,x,y):improvedWashAt(ctx,x,y);
  const legacyGalaxyAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";const cs=["#7A4FBF","#2FA9A0","#FF5DA2","#E8B14B","#fff"];const n=8+Math.round(Math.random()*6);for(let d=0;d<n;d++){const a=Math.random()*Math.PI*2,r=Math.random()*size;ctx.fillStyle=cs[d%cs.length];ctx.globalAlpha=0.3+Math.random()*0.4;ctx.beginPath();ctx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r,1+Math.random()*2,0,Math.PI*2);ctx.fill();}ctx.fillStyle=color;ctx.globalAlpha=0.6;ctx.beginPath();ctx.arc(x,y,size*0.3,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const improvedGalaxyAt=(ctx,x,y)=>{const p=pct();const pr=p.pressure;const es=size*(0.3+pr*0.7);const cs=["#7A4FBF","#2FA9A0","#FF5DA2","#E8B14B","#fff","#4EBFFF","#FF8C42"];ctx.globalCompositeOperation="source-over";const n=20+Math.round(pr*15);for(let d=0;d<n;d++){const a=Math.random()*Math.PI*2,r=Math.random()*es;const cluster=Math.random()<0.3?Math.random()*es*0.3:r;ctx.fillStyle=cs[d%cs.length];ctx.globalAlpha=0.2+Math.random()*0.4*pr;ctx.beginPath();ctx.arc(x+Math.cos(a)*cluster,y+Math.sin(a)*cluster,0.8+Math.random()*2.5,0,Math.PI*2);ctx.fill();}ctx.fillStyle=color;ctx.globalAlpha=0.5*pr;ctx.beginPath();ctx.arc(x,y,es*0.35,0,Math.PI*2);ctx.fill();const g=ctx.createRadialGradient(x,y,0,x,y,es*1.5);g.addColorStop(0,color+"88");g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.globalAlpha=0.15;ctx.beginPath();ctx.arc(x,y,es*1.5,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;};
  const galaxyAt=(ctx,x,y)=>legacyRef.current?legacyGalaxyAt(ctx,x,y):improvedGalaxyAt(ctx,x,y);
  const partialPatternAt=(ctx,x,y)=>{ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;ctx.globalAlpha=0.15;const ps=[[x-size,y-size],[x,y-size],[x+size,y-size],[x-size,y],[x,y],[x+size,y],[x-size,y+size],[x,y+size],[x+size,y+size]];ps.forEach(([px,py])=>{ctx.fillRect(px,py,size*0.7,size*0.7);});ctx.globalAlpha=1;};
  const symXY=(x,y)=>{const o=[[x,y]];if(symmetry==="mirrorX"||symmetry==="quad")o.push([W-x,y]);if(symmetry==="mirrorY"||symmetry==="quad")o.push([x,H-y]);if(symmetry==="quad")o.push([W-x,H-y]);if(symmetry.startsWith("radial")){const n=+symmetry.slice(6),cx=W/2,cy=H/2;for(let i=1;i<n;i++){const a=(i/n)*Math.PI*2,c=Math.cos(a),s=Math.sin(a);o.push([cx+(x-cx)*c-(y-cy)*s,cy+(x-cx)*s+(y-cy)*c]);}}return o;};
  const brushFn=brush==="spray"?sprayAt:brush==="glow"?glowAt:brush==="watercolor"?watercolorAt:brush==="pattern"?partialPatternAt:brush==="calligraphy"?calligraphyAt:brush==="neon"?neonAt:brush==="sparkle"?sparkleAt:brush==="crayon"?crayonAt:brush==="wash"?washAt:brush==="galaxy"?galaxyAt:brush==="custom"?customAt:null;
  const stamp=(ctx,x,y,start)=>{
    const pts=symXY(x,y);
    if(brushFn){pts.forEach(([sx,sy])=>brushFn(ctx,sx,sy));return;}
    if(tool==="soft"||brush==="chalk"){pts.forEach(([sx,sy])=>dabAt(ctx,sx,sy));return;}
    if(start){lastPts.current=pts.map(p=>[...p]);midPts.current=pts.map(p=>[...p]);
      ctx.globalCompositeOperation=tool==="eraser"?"destination-out":"source-over";ctx.fillStyle=color;ctx.globalAlpha=brush==="marker"&&tool!=="eraser"?0.55:1;
      pts.forEach(([sx,sy])=>{ctx.beginPath();ctx.arc(sx,sy,(tool==="eraser"?size*2.4:brush==="marker"?size*1.7:size)/2,0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;return;}
    ctx.globalCompositeOperation=tool==="eraser"?"destination-out":"source-over";ctx.strokeStyle=color;ctx.lineWidth=tool==="eraser"?size*2.4:brush==="marker"?size*1.7:size;ctx.globalAlpha=brush==="marker"&&tool!=="eraser"?0.55:1;ctx.lineCap="round";ctx.lineJoin="round";
    pts.forEach(([sx,sy],i)=>{const lp=lastPts.current[i]||[sx,sy];const mp=midPts.current[i]||lp;const nmx=(lp[0]+sx)/2,nmy=(lp[1]+sy)/2;ctx.beginPath();ctx.moveTo(mp[0],mp[1]);ctx.quadraticCurveTo(lp[0],lp[1],nmx,nmy);ctx.stroke();midPts.current[i]=[nmx,nmy];lastPts.current[i]=[sx,sy];});
    ctx.globalAlpha=1;
  };
  const fillLayer=ctx=>{ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;ctx.fillRect(0,0,W,H);};
  const eyedrop=(x,y)=>{for(let i=layers.length-1;i>=0;i--){const cv=canvases.current.get(layers[i].id);if(!cv||!layers[i].visible)continue;const d=cv.getContext("2d").getImageData(Math.floor(x),Math.floor(y),1,1).data;if(d[3]>10){setColorAndRecent(`rgb(${d[0]},${d[1]},${d[2]})`);setTool("pen");return;}}};
  const down=e=>{e.preventDefault();const cv=canvases.current.get(active);if(!cv||!activeLayer?.visible)return;e.currentTarget.setPointerCapture(e.pointerId);const p0=pos(e);const mul=dynMul(e,p0[0],p0[1]);pointerRef.current={pressure:e.pointerType==="pen"&&e.pressure>0?e.pressure:mul,tiltX:e.tiltX||0,tiltY:e.tiltY||0,twist:e.twist||0,pointerType:e.pointerType||"mouse"};if(tool==="eyedrop"){eyedrop(...p0);return;}if(tool==="transform"){transformDrag.current={startClient:[e.clientX,e.clientY],startCanvas:p0};return;}pushUndo();if(tool==="fill"){fillLayer(cv.getContext("2d"));return;}if(tool==="clone"){if(!clonePt){setClonePt(p0);return;}const[ox,oy]=clonePt;const[cx,cy]=p0;const src=cv.getContext("2d").getImageData(Math.floor(ox),Math.floor(oy),48,60);cv.getContext("2d").putImageData(src,Math.floor(cx)-24,Math.floor(cy)-30);setClonePt(null);return;}if(tool==="shape"){setAnchorPt(p0);drawing.current=true;return;}if(tool==="gradient"){setAnchorPt(p0);drawing.current=true;return;}drawing.current=true;onStroke&&onStroke();stamp(cv.getContext("2d"),...p0,true);};
  const move=e=>{if(tool==="transform"){if(!transformDrag.current)return;const cv=canvases.current.get(active);if(cv)cv.style.transform=`translate(${e.clientX-transformDrag.current.startClient[0]}px,${e.clientY-transformDrag.current.startClient[1]}px)`;return;}if(!drawing.current&&tool!=="push"&&tool!=="smudge")return;const cv=canvases.current.get(active);if(!cv)return;const ctx=cv.getContext("2d");const evs=(e.getCoalescedEvents&&e.getCoalescedEvents().length)?e.getCoalescedEvents():[e];const p=pos(evs[evs.length-1]);const mul=dynMul(e,p[0],p[1]);pointerRef.current={pressure:e.pointerType==="pen"&&e.pressure>0?e.pressure:mul,tiltX:e.tiltX||0,tiltY:e.tiltY||0,twist:e.twist||0,pointerType:e.pointerType||"mouse"};if(tool==="push"){ctx.globalCompositeOperation="source-over";const[x,y]=p;const d=ctx.getImageData(Math.max(0,Math.floor(x)-size),Math.max(0,Math.floor(y)-size),size*2,size*2);ctx.putImageData(d,Math.max(0,Math.floor(x)-size+2),Math.max(0,Math.floor(y)-size+2));return;}if(tool==="smudge"){const[x,y]=p;const rx=Math.max(0,Math.floor(x)-8),ry=Math.max(0,Math.floor(y)-8);const d=ctx.getImageData(rx,ry,20,20);for(let i=0;i<d.data.length;i+=4){d.data[i]=(d.data[i]+d.data[i+4]+d.data[i-4]||d.data[i])/3;d.data[i+1]=(d.data[i+1]+d.data[i+5]+d.data[i-3]||d.data[i+1])/3;d.data[i+2]=(d.data[i+2]+d.data[i+6]+d.data[i-2]||d.data[i+2])/3;}ctx.putImageData(d,rx,ry);return;}if(tool==="shape"||tool==="gradient"){lastPts.current=[[p[0],p[1]]];return;}evs.forEach(ev=>stamp(ctx,...pos(ev),false));};
  const up=e=>{if(tool==="transform"){const cv=canvases.current.get(active);if(cv)cv.style.transform="";if(transformDrag.current&&e){const p1=pos(e);const[sx,sy]=transformDrag.current.startCanvas;const dx=p1[0]-sx,dy=p1[1]-sy;if(Math.abs(dx)>0.5||Math.abs(dy)>0.5)commitTranslate(dx,dy);}transformDrag.current=null;return;}drawing.current=false;if(tool==="shape"&&anchorPt){const cv=canvases.current.get(active);if(cv){const ctx=cv.getContext("2d");const[ax,ay]=anchorPt;const[sx,sy]=lastPts.current[0]||[ax,ay];const x=Math.min(ax,sx),y=Math.min(ay,sy),w=Math.abs(sx-ax),h=Math.abs(sy-ay);ctx.globalCompositeOperation="source-over";ctx.fillStyle=color;if(shapeMode==="ellipse")ctx.beginPath(),ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2),ctx.fill();else ctx.fillRect(x,y,w,h);ctx.globalAlpha=1;}setAnchorPt(null);}if(tool==="gradient"&&anchorPt){const cv=canvases.current.get(active);if(cv){const ctx=cv.getContext("2d");const[ax,ay]=anchorPt;const[sx,sy]=lastPts.current[0]||[ax,ay];const g=ctx.createLinearGradient(ax,ay,sx,sy);g.addColorStop(0,color);g.addColorStop(0.5,color);g.addColorStop(1,T.paper);ctx.globalCompositeOperation="source-over";ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}setAnchorPt(null);}lastPts.current=[];midPts.current=[];};
  const undo=()=>{const u=undoStack.current.pop();if(!u)return;const cv=canvases.current.get(u.id);if(cv){redoStack.current.push({id:u.id,snap:cv.getContext("2d").getImageData(0,0,W,H)});cv.getContext("2d").putImageData(u.snap,0,0);}};
  const redo=()=>{const r=redoStack.current.pop();if(!r)return;const cv=canvases.current.get(r.id);if(cv){undoStack.current.push({id:r.id,snap:cv.getContext("2d").getImageData(0,0,W,H)});cv.getContext("2d").putImageData(r.snap,0,0);}};
  const addLayer=()=>{if(layers.length>=maxLayers)return;const id=++idRef.current;setLayers(ls=>[...ls,{id,visible:true,opacity:1,blend:"source-over"}]);setActive(id);};
  const removeLayer=id=>{if(layers.length<=1)return;canvases.current.delete(id);setLayers(ls=>{const next=ls.filter(l=>l.id!==id);if(active===id)setActive(next[next.length-1].id);return next;});};
  const patchLayer=(id,p)=>setLayers(ls=>ls.map(l=>(l.id===id?{...l,...p}:l)));
  const setColorAndRecent=c=>{setColor(c);if(tool==="eraser")setTool("pen");setRecentColors(r=>[c,...r.filter(x=>x!==c)].slice(0,8));};
  const blurLayer=(ctx,r)=>{const d=ctx.getImageData(0,0,W,H);ctx.clearRect(0,0,W,H);for(let y=r;y<H-r;y++){for(let x=r;x<W-r;x++){let r2=0,g=0,b=0,a=0,n=0;for(let dy=-r;dy<=r;dy++){for(let dx=-r;dx<=r;dx++){const i=((y+dy)*W+(x+dx))*4;r2+=d.data[i];g+=d.data[i+1];b+=d.data[i+2];a+=d.data[i+3];n++;}}ctx.fillStyle="rgba("+(r2/n|0)+","+(g/n|0)+","+(b/n|0)+","+(a/n)+")";ctx.fillRect(x,y,1,1);}}};
  const replaceColor=(ctx,fromColor)=>{const d=ctx.getImageData(0,0,W,H);let tc;{const m=fromColor.match(/rgb\((\d+),\s*(\d+),\s*(\d+)\)/);if(m){tc={r:+m[1],g:+m[2],b:+m[3]};}else{const c=document.createElement("canvas").getContext("2d");c.fillStyle=fromColor;c.fillRect(0,0,1,1);const p=c.getImageData(0,0,1,1).data;tc={r:p[0],g:p[1],b:p[2]};}}const R=30;for(let i=0;i<d.data.length;i+=4){const dr=d.data[i]-tc.r,dg=d.data[i+1]-tc.g,db=d.data[i+2]-tc.b;if(dr*dr+dg*dg+db*db<R*R){d.data[i]=255;d.data[i+1]=255;d.data[i+2]=255;}}ctx.putImageData(d,0,0);};
  const swatches=hasModule(modules,"feat_palettes")&&PALLETS[palette]?PALLETS[palette]:PALLETS.default;
  return(<div>
    <div ref={wrapRef} className="relative rounded-2xl overflow-hidden select-none" style={{border:`3px solid ${T.ink}`,background:ART.paper,boxShadow:`6px 6px 0 ${T.shadow}`,aspectRatio:"4 / 5",cursor:zoom!==1?"grab":"default"}}
      onWheel={e=>{e.preventDefault();const d=e.deltaY>0?-0.1:0.1;const r=wrapRef.current?.getBoundingClientRect();if(!r)return;const mx=(e.clientX-r.left)/r.width,my=(e.clientY-r.top)/r.height;setZoom(z=>{const nz=Math.max(0.25,Math.min(4,z+d));setPan(p=>({x:mx-(mx-p.x)*nz/z,y:my-(my-p.y)*nz/z}));return nz;});}}
      onTouchStart={e=>{if(e.touches.length===2){e.preventDefault();const dx=e.touches[0].clientX-e.touches[1].clientX,dy=e.touches[0].clientY-e.touches[1].clientY;pinchRef.current={dist:Math.sqrt(dx*dx+dy*dy),zoom:zoom};}}}
      onTouchMove={e=>{if(e.touches.length===2&&pinchRef.current){e.preventDefault();const dx=e.touches[0].clientX-e.touches[1].clientX,dy=e.touches[0].clientY-e.touches[1].clientY;const nd=Math.sqrt(dx*dx+dy*dy);const d=nd/pinchRef.current.dist;const r=wrapRef.current?.getBoundingClientRect();if(!r)return;const mx=((e.touches[0].clientX+e.touches[1].clientX)/2-r.left)/r.width,my=((e.touches[0].clientY+e.touches[1].clientY)/2-r.top)/r.height;setZoom(z=>{const nz=Math.max(0.25,Math.min(4,pinchRef.current.zoom*d));setPan(p=>({x:mx-(mx-p.x)*nz/z,y:my-(my-p.y)*nz/z}));return nz;});}}}
      onTouchEnd={e=>{if(e.touches.length<2)pinchRef.current=null;}}
      onMouseDown={e=>{if(e.button===1){e.preventDefault();isPanning.current=true;panStart.current={x:e.clientX-pan.x,y:e.clientY-pan.y};}}}
      onMouseMove={e=>{if(!isPanning.current)return;setPan({x:e.clientX-panStart.current.x,y:e.clientY-panStart.current.y});}}
      onMouseUp={()=>{isPanning.current=false;}}
      onContextMenu={e=>{if(e.button===1){e.preventDefault();}}}>
      <div style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`,transformOrigin:"0 0",width:zoom===1?"100%":undefined}}>
      {onionFrames.map((of,i)=>(<img key={i} src={of.src} alt="" aria-hidden="true" className="absolute inset-0 w-full h-full pointer-events-none" style={{opacity:of.opacity,mixBlendMode:"multiply"}}/>))}
      {refImg&&<img src={refImg} alt="" aria-hidden="true" className="absolute inset-0 w-full h-full pointer-events-none" style={{opacity:refOpacity}}/>}
      {layers.map(l=>(<canvas key={l.id} width={W} height={H} ref={el=>{if(el){canvases.current.set(l.id,el);el.getContext("2d",{willReadFrequently:true});}}} aria-hidden="true" className="absolute inset-0 w-full h-full" style={{opacity:l.opacity,display:l.visible?"block":"none",mixBlendMode:l.blend==="source-over"?"normal":l.blend}}/>))}
      <div className="absolute inset-0" style={{touchAction:"none",cursor:pointerRef.current.pointerType==="pen"?"crosshair":"crosshair"}} role="img" aria-label="Drawing canvas" onPointerDown={down} onPointerMove={e=>{move(e);const r=wrapRef.current?.getBoundingClientRect();if(r)setCursorPos([(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100]);}} onPointerUp={e=>{up(e);setCursorPos(null);}} onPointerLeave={e=>{up(e);setCursorPos(null);}}/>
      {cursorPos&&(tool==="pen"||tool==="soft"||tool==="eraser")&&<div aria-hidden="true" className="absolute pointer-events-none" style={{left:`${cursorPos[0]}%`,top:`${cursorPos[1]}%`,width:tool==="eraser"?size*2.4:brush==="marker"?size*1.7:size,height:tool==="eraser"?size*2.4:brush==="marker"?size*1.7:size,borderRadius:"50%",border:`2px solid ${T.accent}`,background:"rgba(255,255,255,.25)",transform:"translate(-50%,-50%)",zIndex:10}}/>}
      {paper==="grid"&&<div aria-hidden="true" className="absolute inset-0 pointer-events-none" style={{backgroundImage:`repeating-linear-gradient(${T.ink}15 0 1px,transparent 1px ${H/10}px),repeating-linear-gradient(90deg,${T.ink}15 0 1px,transparent 1px ${W/10}px)`,zIndex:5}}/>}
      {paper==="dots"&&<div aria-hidden="true" className="absolute inset-0 pointer-events-none" style={{backgroundImage:`radial-gradient(circle,${T.ink}25 1px,transparent 1px)`,backgroundSize:`${W/10}px ${H/10}px`,zIndex:5}}/>}
      {paper==="storyboard"&&<div aria-hidden="true" className="absolute inset-0 pointer-events-none" style={{backgroundImage:[`linear-gradient(${T.ink}20 0 1px,transparent 1px)`,`linear-gradient(90deg,${T.ink}20 0 1px,transparent 1px)`].join(","),backgroundSize:[`100% ${H/3}px`,`${W/2}px 100%`].join(","),zIndex:5}}><div className="absolute left-1/2 top-0 bottom-0" style={{width:1,background:T.ink+"30"}}/><div className="absolute top-[33.33%] left-0 right-0" style={{height:1,background:T.ink+"30"}}/><div className="absolute top-[66.66%] left-0 right-0" style={{height:1,background:T.ink+"30"}}/></div>}
      {paper==="graphite"&&<div aria-hidden="true" className="absolute inset-0 pointer-events-none" style={{background:`repeating-conic-gradient(${T.ink}08 0% 25%,transparent 0% 50%) 0 0 / 4px 4px`,opacity:0.5,zIndex:5}}/>}
      {(symmetry==="mirrorX"||symmetry==="quad")&&<div aria-hidden="true" className="absolute top-0 bottom-0 pointer-events-none" style={{left:"50%",width:2,background:`repeating-linear-gradient(${T.accent} 0 6px, transparent 6px 12px)`}}/>}
      {(symmetry==="mirrorY"||symmetry==="quad")&&<div aria-hidden="true" className="absolute left-0 right-0 pointer-events-none" style={{top:"50%",height:2,background:`repeating-linear-gradient(90deg,${T.accent} 0 6px, transparent 6px 12px)`}}/>}
      {symmetry.startsWith("radial")&&<div aria-hidden="true" className="absolute pointer-events-none rounded-full" style={{left:"50%",top:"50%",width:10,height:10,transform:"translate(-50%,-50%)",border:`2.5px solid ${T.accent}`}}/>}
      <div className="absolute top-1.5 left-1.5 lok-display px-2 py-0.5 rounded-md text-xs font-extrabold pointer-events-none" style={{background:"rgba(35,48,107,.85)",color:T.paper,backdropFilter:"blur(3px)"}}>L{layers.findIndex(l=>l.id===active)+1} / {layers.length}</div>
      {canvasSize!=="default"&&(<div aria-hidden="true" className="absolute inset-0 pointer-events-none flex items-center justify-center" style={{zIndex:6}}><div style={{width:canvasSize==="story"?"37.5%":canvasSize==="square"?"80%":canvasSize==="wide"?"100%":"100%",height:canvasSize==="story"?"100%":canvasSize==="square"?"80%":canvasSize==="wide"?"56.25%":"100%",border:`2px dashed ${T.accent}`,opacity:0.5}}/></div>)}
    </div>
    {zoom!==1&&<div className="absolute top-1.5 right-1.5 px-1.5 py-0.5 rounded-md text-[10px] font-bold pointer-events-none" style={{background:"rgba(0,0,0,.6)",color:"#fff"}}>{Math.round(zoom*100)}%</div>}
    </div>
    <div className="mt-2 flex items-center gap-1.5 overflow-x-auto pb-1" role="toolbar" aria-label="Layer controls">
      {layers.map((l,i)=>(<div key={l.id} className="shrink-0 flex items-center gap-1 px-1.5 py-1 rounded-lg" style={{border:`2.5px solid ${l.id===active?T.accent:T.ink}`,background:l.id===active?T.card:"transparent"}}>
        <button onClick={()=>setActive(l.id)} aria-label={`Select layer ${i+1}`} aria-pressed={l.id===active} className="font-bold text-xs px-1" style={{color:T.ink}}>L{i+1}</button>
        <button onClick={()=>patchLayer(l.id,{visible:!l.visible})} aria-label={l.visible?`Hide layer ${i+1}`:`Show layer ${i+1}`} className="text-xs font-bold w-5" style={{color:T.ink,opacity:l.visible?1:0.35}}>{l.visible?"●":"○"}</button>
        {layers.length>1&&<button onClick={()=>removeLayer(l.id)} aria-label={`Delete layer ${i+1}`} className="text-xs font-bold" style={{color:T.accent}}>✕</button>}
      </div>))}
      <button onClick={addLayer} disabled={layers.length>=maxLayers} aria-label="Add layer" className="shrink-0 px-2.5 py-1 rounded-lg font-extrabold text-sm" style={{border:`2.5px solid ${T.ink}`,color:T.ink,opacity:layers.length>=maxLayers?0.35:1,background:T.card}}>+ layer</button>
      {activeLayer&&<label className="shrink-0 flex items-center gap-1.5 text-xs font-bold ml-1" style={{color:T.ink}}>opacity<input type="range" min="0.1" max="1" step="0.05" value={activeLayer.opacity} onChange={e=>patchLayer(active,{opacity:+e.target.value})} style={{accentColor:T.accent,width:64}} aria-label="Layer opacity"/></label>}
    </div>
    {hasModule(modules,"feat_blend")&&activeLayer&&(<div className="mt-1.5 flex items-center gap-1.5 overflow-x-auto pb-1" role="toolbar" aria-label="Blend modes">
      <span className="text-xs font-bold opacity-60 shrink-0">blend</span>
      {BLENDS.map(b=>(<button key={b} onClick={()=>patchLayer(active,{blend:b})} aria-pressed={activeLayer.blend===b} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[11px] font-bold" style={{border:`2px solid ${activeLayer.blend===b?T.accent:T.ink}`,background:activeLayer.blend===b?T.ink:T.card,color:activeLayer.blend===b?T.paper:T.ink}}>{{"source-over":"normal","color-dodge":"dodge","color-burn":"burn","hard-light":"h.light","soft-light":"s.light"}[b]||b}</button>))}
    </div>)}
    <div className="mt-1.5 flex items-center gap-1.5 overflow-x-auto pb-1" role="toolbar" aria-label="Tools">
      {[["fill","Fill"],["eyedrop","Eyedrop"]].map(([id,l])=>(<button key={id} onClick={()=>setTool(id)} aria-pressed={tool===id} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[11px] font-bold" style={{border:`2px solid ${tool===id?T.accent:T.ink}`,background:tool===id?T.ink:T.card,color:tool===id?T.paper:T.ink}}>{l}</button>))}
      <button onClick={()=>setBrushLabOpen(o=>!o)} aria-pressed={brushLabOpen} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[11px] font-bold" style={{border:`2px solid ${brushLabOpen?T.accent:T.ink}`,background:brushLabOpen?T.ink:T.card,color:brushLabOpen?T.paper:T.ink}}>Brush Lab</button>
      <button onClick={()=>setDynamics(d=>!d)} aria-pressed={dynamics} title="Pressure & speed-based size dynamics" className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${dynamics?T.accent:T.ink}`,background:dynamics?T.ink:T.card,color:dynamics?T.paper:T.ink}}>Dynamics</button>
      {showPro&&(<div className="flex items-center gap-1.5"><span className="text-xs font-bold opacity-60 shrink-0">pro</span>
        {brushList.map(([id,l])=>(<button key={id} onClick={()=>{setBrush(id);if(tool==="eraser"||tool==="fill"||tool==="eyedrop")setTool("pen");}} aria-pressed={brush===id} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[11px] font-bold" style={{border:`2px solid ${brush===id?T.accent:T.ink}`,background:brush===id?T.ink:T.card,color:brush===id?T.paper:T.ink}}>{l}</button>))}
        {hasSym&&<select value={symmetry} onChange={e=>setSymmetry(e.target.value)} aria-label="Symmetry mode" className="shrink-0 px-2 py-1 rounded-full text-[11px] font-bold" style={{border:`2px solid ${symmetry!=="none"?T.accent:T.ink}`,background:symmetry!=="none"?T.ink:T.card,color:symmetry!=="none"?T.paper:T.ink}}>
          <option value="none">No symmetry</option><option value="mirrorX">Mirror X</option><option value="mirrorY">Mirror Y</option><option value="quad">4-Way</option><option value="radial4">Radial 4</option><option value="radial6">Radial 6</option><option value="radial8">Radial 8</option>
        </select>}</div>)}
    </div>
    {brushLabOpen&&(<div className="mt-1.5 p-2.5 rounded-xl flex flex-col gap-2" style={{border:`2.5px solid ${T.ink}`,background:T.card}}>
      <div className="flex items-center gap-2">
        <canvas ref={labPreviewRef} width={220} height={48} aria-label="Brush preview" className="rounded-lg" style={{border:`2px solid ${T.ink}`,background:ART.paper,width:220,height:48}}/>
      </div>
      <div className="flex flex-wrap gap-1.5">
        {DEMO_BRUSH_PRESETS.map(p=>(<button key={p.id} onClick={()=>applyBrushPreset(p)} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.paper,color:T.ink}}>{p.name}</button>))}
        {savedBrushes.map(p=>(<button key={p.id} onClick={()=>applyBrushPreset(p)} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.accent}`,background:T.paper,color:T.ink}}>{p.name}</button>))}
      </div>
      <div className="flex flex-wrap gap-x-3 gap-y-1.5 text-[10px] font-bold" style={{color:T.ink}}>
        <label className="flex items-center gap-1">Flow<input type="range" min="0.02" max="1" step="0.01" value={customBrushParams.flow} onChange={e=>setCustomBrushParams(p=>({...p,flow:+e.target.value}))} style={{accentColor:T.accent,width:56}} aria-label="Brush flow"/></label>
        <label className="flex items-center gap-1">Scatter<input type="range" min="0" max="1" step="0.01" value={customBrushParams.scatter} onChange={e=>setCustomBrushParams(p=>({...p,scatter:+e.target.value}))} style={{accentColor:T.accent,width:56}} aria-label="Brush scatter"/></label>
        <label className="flex items-center gap-1">Dabs<input type="range" min="1" max="10" step="1" value={customBrushParams.dabs} onChange={e=>setCustomBrushParams(p=>({...p,dabs:+e.target.value}))} style={{accentColor:T.accent,width:56}} aria-label="Brush dab count"/></label>
        <label className="flex items-center gap-1">Jitter<input type="range" min="0" max="1" step="0.01" value={customBrushParams.angleJitter} onChange={e=>setCustomBrushParams(p=>({...p,angleJitter:+e.target.value}))} style={{accentColor:T.accent,width:56}} aria-label="Brush angle jitter"/></label>
        <label className="flex items-center gap-1">Round<input type="range" min="0.2" max="1" step="0.01" value={customBrushParams.roundness} onChange={e=>setCustomBrushParams(p=>({...p,roundness:+e.target.value}))} style={{accentColor:T.accent,width:56}} aria-label="Brush roundness"/></label>
      </div>
      <div className="flex items-center gap-2">
        <button onClick={useCustomBrush} className="lok-btn px-3 py-1 rounded-full text-[11px] font-extrabold" style={{border:`2.5px solid ${T.accent}`,background:brush==="custom"?T.ink:T.card,color:brush==="custom"?T.paper:T.ink}}>Use this brush</button>
        {hasBrushLabSave?<button onClick={saveBrushPreset} className="lok-btn px-3 py-1 rounded-full text-[11px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.card,color:T.ink}}>Save preset</button>:<span className="text-[10px] font-bold opacity-70">Unlock Brush Lab Save to keep custom presets</span>}
      </div>
    </div>)}
    <div className="mt-2 flex flex-wrap items-center gap-2" role="toolbar" aria-label="Color and tools">
      <div className="flex flex-wrap gap-1.5 items-center">
        {swatches.map(hex=>(<button key={hex} onClick={()=>setColorAndRecent(hex)} aria-label={`Color ${hex}`} aria-pressed={color===hex&&tool!=="eraser"} className="lok-btn w-7 h-7 rounded-full" style={{background:hex,border:`3px solid ${color===hex&&tool!=="eraser"?T.accent:T.ink}`,transform:color===hex&&tool!=="eraser"?"scale(1.18)":"none"}}/>))}
        <label aria-label="Custom color" style={{cursor:"pointer"}}>
          <div className="w-7 h-7 rounded-full flex items-center justify-center text-[11px] font-bold" style={{border:`3px dashed ${T.ink}`,background:T.card,color:T.ink}}>+</div>
          <input type="color" value={color} onChange={e=>setColorAndRecent(e.target.value)} style={{position:"absolute",opacity:0,width:1,height:1}}/>
        </label>
        {recentColors.map(hex=>(<button key={"r"+hex} onClick={()=>setColorAndRecent(hex)} aria-label={`Recent ${hex}`} className="lok-btn w-5 h-5 rounded-full" style={{background:hex,border:`2px solid ${T.shadow}`}}/>))}
        {hasModule(modules,"feat_palettes")&&<select value={palette} onChange={e=>setPalette(e.target.value)} aria-label="Color palette" className="ml-1 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${palette!=="default"?T.accent:T.ink}`,background:palette!=="default"?T.ink:T.card,color:palette!=="default"?T.paper:T.ink}}>{Object.keys(PALLETS).map(k=><option key={k} value={k}>{k}</option>)}</select>}
      </div>
      <button onClick={()=>setTool("pen")} aria-pressed={tool==="pen"} className="lok-btn px-2.5 h-8 rounded-full font-bold text-xs" style={{border:`3px solid ${tool==="pen"?T.accent:T.ink}`,background:T.card,color:T.ink}}>Pen</button>
      {hasModule(modules,"brush_air")&&<button onClick={()=>setTool("soft")} aria-pressed={tool==="soft"} className="lok-btn px-2.5 h-8 rounded-full font-bold text-xs" style={{border:`3px solid ${tool==="soft"?T.accent:T.ink}`,background:T.card,color:T.ink}}>Airbrush</button>}
      <button onClick={()=>setTool("eraser")} aria-pressed={tool==="eraser"} className="lok-btn px-2.5 h-8 rounded-full font-bold text-xs" style={{border:`3px solid ${tool==="eraser"?T.accent:T.ink}`,background:T.card,color:T.ink}}>Eraser</button>
      <label className="flex items-center gap-1.5 text-xs font-bold" style={{color:T.ink}}>
        size<span className="inline-flex items-center justify-center" style={{width:28,height:28}}><span aria-hidden="true" style={{width:Math.max(4,Math.min(24,size)),height:Math.max(4,Math.min(24,size)),borderRadius:"50%",background:tool==="eraser"?"transparent":color,border:`1.5px solid ${T.ink}`,display:"block"}}/></span>
        <input type="range" min="1" max="160" value={size} onChange={e=>setSize(+e.target.value)} style={{accentColor:T.accent,width:56}} aria-label={`Brush size ${size}px`}/>
        <input type="number" min="1" max="400" value={size} onChange={e=>setSize(Math.max(1,Math.min(400,+e.target.value||1)))} className="text-[10px] font-bold rounded px-1" style={{width:38,border:`1.5px solid ${T.ink}`,color:T.ink,background:T.paper}} aria-label="Exact brush size"/>
      </label>
      <button onClick={undo} aria-label="Undo" className="lok-btn px-2.5 h-8 rounded-full font-bold text-xs" style={{border:`3px solid ${T.ink}`,background:T.card,color:T.ink}}>Undo</button>
      <button onClick={redo} aria-label="Redo" className="lok-btn px-2.5 h-8 rounded-full font-bold text-xs" style={{border:`3px solid ${T.ink}`,background:T.card,color:T.ink}}>Redo</button>
      {hasModule(modules,"brush_legacy_pack")&&<button onClick={e=>{const nxt=!legacyRef.current;legacyRef.current=nxt;onLegacyToggle&&onLegacyToggle(nxt);}} className="lok-btn px-2 h-8 rounded-full font-bold text-[10px]" style={{border:`2px solid ${legacyRef.current?T.accent:T.ink}`,background:legacyRef.current?T.ink:T.card,color:legacyRef.current?T.paper:T.ink}} title="Toggle legacy brush engine">{legacyRef.current?"Legacy":"Modern"}</button>}
    </div>
    {hasTools&&(<div className="mt-1.5 flex items-center gap-1 overflow-x-auto pb-1" role="toolbar" aria-label="Studio upgrades">
      {hasModule(modules,"tool_spray")&&<button onClick={()=>{setBrush("spray");setTool("pen");}} aria-pressed={brush==="spray"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${brush==="spray"?T.accent:T.ink}`,background:brush==="spray"?T.ink:T.card,color:brush==="spray"?T.paper:T.ink}}>Spray</button>}
      {hasModule(modules,"tool_glow")&&<button onClick={()=>{setBrush("glow");setTool("pen");}} aria-pressed={brush==="glow"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${brush==="glow"?T.accent:T.ink}`,background:brush==="glow"?T.ink:T.card,color:brush==="glow"?T.paper:T.ink}}>Glow</button>}
      {hasModule(modules,"tool_watercolor")&&<button onClick={()=>{setBrush("watercolor");setTool("pen");}} aria-pressed={brush==="watercolor"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${brush==="watercolor"?T.accent:T.ink}`,background:brush==="watercolor"?T.ink:T.card,color:brush==="watercolor"?T.paper:T.ink}}>Watercolor</button>}
      {hasModule(modules,"tool_pattern")&&<button onClick={()=>{setBrush("pattern");setTool("pen");}} aria-pressed={brush==="pattern"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${brush==="pattern"?T.accent:T.ink}`,background:brush==="pattern"?T.ink:T.card,color:brush==="pattern"?T.paper:T.ink}}>Pattern</button>}
      {hasModule(modules,"tool_shape")&&<button onClick={()=>setTool(tool==="shape"?"pen":"shape")} aria-pressed={tool==="shape"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${tool==="shape"?T.accent:T.ink}`,background:tool==="shape"?T.ink:T.card,color:tool==="shape"?T.paper:T.ink}}>Shape</button>}
      {hasModule(modules,"tool_shape")&&tool==="shape"&&<select value={shapeMode} onChange={e=>setShapeMode(e.target.value)} className="shrink-0 px-1.5 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`}}><option value="rect">Rect</option><option value="ellipse">Ellipse</option></select>}
      {hasModule(modules,"tool_gradient")&&<button onClick={()=>setTool(tool==="gradient"?"pen":"gradient")} aria-pressed={tool==="gradient"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${tool==="gradient"?T.accent:T.ink}`,background:tool==="gradient"?T.ink:T.card,color:tool==="gradient"?T.paper:T.ink}}>Gradient</button>}
      {hasModule(modules,"tool_push")&&<button onClick={()=>setTool(tool==="push"?"pen":"push")} aria-pressed={tool==="push"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${tool==="push"?T.accent:T.ink}`,background:tool==="push"?T.ink:T.card,color:tool==="push"?T.paper:T.ink}}>Push</button>}
      {hasModule(modules,"tool_smudge")&&<button onClick={()=>setTool(tool==="smudge"?"pen":"smudge")} aria-pressed={tool==="smudge"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${tool==="smudge"?T.accent:T.ink}`,background:tool==="smudge"?T.ink:T.card,color:tool==="smudge"?T.paper:T.ink}}>Smudge</button>}
      {hasModule(modules,"tool_clone")&&<button onClick={()=>{setTool("clone");setClonePt(null);}} aria-pressed={tool==="clone"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${tool==="clone"?T.accent:T.ink}`,background:tool==="clone"?T.ink:T.card,color:tool==="clone"?T.paper:T.ink}}>{tool==="clone"&&clonePt?"Stamp·Click":"Clone"}</button>}
       {hasModule(modules,"tool_blur")&&<><button onClick={()=>{const cv=canvases.current.get(active);if(!cv||!activeLayer?.visible)return;pushUndo();blurLayer(cv.getContext("2d"),blurAmount);}} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:"2px solid "+T.ink,background:T.card,color:T.ink}}>Blur {'\u00D7'} <span>{blurAmount}</span></button><input type="range" min="1" max="12" value={blurAmount} onChange={e=>setBlurAmount(+e.target.value)} style={{accentColor:T.accent,width:40}} aria-label="Blur radius"/></>}
      {hasModule(modules,"tool_replace")&&<button onClick={()=>{const cv=canvases.current.get(active);if(!cv||!activeLayer?.visible)return;pushUndo();replaceColor(cv.getContext("2d"),color);}} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:"2px solid "+T.ink,background:T.card,color:T.ink}}>Replace&rarr;W</button>}
      {hasModule(modules,"tool_rulers")&&<button onClick={()=>setShowGuides(g=>!g)} aria-pressed={showGuides} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${showGuides?T.accent:T.ink}`,background:showGuides?T.ink:T.card,color:showGuides?T.paper:T.ink}}>Rulers</button>}
      {hasModule(modules,"tool_transform")&&<button onClick={()=>setTool(tool==="transform"?"pen":"transform")} aria-pressed={tool==="transform"} className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${tool==="transform"?T.accent:T.ink}`,background:tool==="transform"?T.ink:T.card,color:tool==="transform"?T.paper:T.ink}}>Transform</button>}
      {hasModule(modules,"tool_transform")&&tool==="transform"&&(<>
        <button onClick={()=>rotateLayer(-90)} aria-label="Rotate left 90" className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.card,color:T.ink}}>↺90</button>
        <button onClick={()=>rotateLayer(90)} aria-label="Rotate right 90" className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.card,color:T.ink}}>↻90</button>
        <button onClick={()=>flipLayer("h")} aria-label="Flip horizontal" className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.card,color:T.ink}}>Flip H</button>
        <button onClick={()=>flipLayer("v")} aria-label="Flip vertical" className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.card,color:T.ink}}>Flip V</button>
        <button onClick={()=>scaleLayer(1.1)} aria-label="Scale up" className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.card,color:T.ink}}>Scale+</button>
        <button onClick={()=>scaleLayer(0.9)} aria-label="Scale down" className="lok-btn shrink-0 px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${T.ink}`,background:T.card,color:T.ink}}>Scale-</button>
      </>)}
      {hasModule(modules,"feat_ref")&&<label className="shrink-0 cursor-pointer"><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=ev=>setRefImg(ev.target.result);r.readAsDataURL(f);e.target.value="";}} style={{display:"none"}}/><span className="lok-btn px-2 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${refImg?T.accent:T.ink}`,background:refImg?T.ink:T.card,color:refImg?T.paper:T.ink}}>{refImg?"Ref ✓":"Ref"}</span></label>}
    </div>)}
    {hasModule(modules,"canvas_sizes")&&(<div className="mt-1.5 flex items-center gap-1.5 overflow-x-auto pb-1" style={{color:T.ink}}>
      <span className="text-[10px] font-bold opacity-60 shrink-0">Size</span>
      {[["default","4:5"],["story","9:16"],["square","1:1"],["wide","16:9"]].map(([id,l])=>(<button key={id} onClick={()=>setCanvasSize(id)} aria-pressed={canvasSize===id} className="lok-btn shrink-0 px-2.5 py-1 rounded-full text-[10px] font-bold" style={{border:`2px solid ${canvasSize===id?T.accent:T.ink}`,background:canvasSize===id?T.ink:T.card,color:canvasSize===id?T.paper:T.ink}}>{l}</button>))}
    </div>)}
    {hasModule(modules,"feat_smooth")&&(<div className="mt-1.5 flex items-center gap-1.5" style={{color:T.ink}}>
      <span className="text-[10px] font-bold">Smooth</span>
      <input type="range" min="0" max="1" step="0.1" value={smoothStrength} onChange={e=>setSmoothStrength(+e.target.value)} style={{accentColor:T.accent,width:50}} aria-label="Stroke smoothing"/>
      <span className="text-[10px] opacity-60">{Math.round(smoothStrength*100)}%</span>
    </div>)}
    {refImg&&hasModule(modules,"feat_ref")&&(<div className="mt-1.5 flex items-center gap-2" style={{color:T.ink}}>
      <span className="text-[10px] font-bold">Ref</span>
      <input type="range" min="0.05" max="0.6" step="0.05" value={refOpacity} onChange={e=>setRefOpacity(+e.target.value)} style={{accentColor:T.accent,width:60}} aria-label="Reference opacity"/>
      <button onClick={()=>setRefImg(null)} className="text-[10px] font-bold underline opacity-60">clear</button>
    </div>)}
    {showGuides&&<div aria-hidden="true" className="absolute inset-0 pointer-events-none" style={{zIndex:20}}><div style={{position:"absolute",left:"33.33%",top:0,bottom:0,width:1,background:`repeating-linear-gradient(${T.alt}40 0 4px,transparent 4px 8px)`}}/><div style={{position:"absolute",left:"66.66%",top:0,bottom:0,width:1,background:`repeating-linear-gradient(${T.alt}40 0 4px,transparent 4px 8px)`}}/><div style={{position:"absolute",top:"33.33%",left:0,right:0,height:1,background:`repeating-linear-gradient(90deg,${T.alt}40 0 4px,transparent 4px 8px)`}}/><div style={{position:"absolute",top:"66.66%",left:0,right:0,height:1,background:`repeating-linear-gradient(90deg,${T.alt}40 0 4px,transparent 4px 8px)`}}/><div style={{position:"absolute",left:"50%",top:0,bottom:0,width:1,background:`repeating-linear-gradient(${T.alt}60 0 6px,transparent 6px 12px)`}}/><div style={{position:"absolute",top:"50%",left:0,right:0,height:1,background:`repeating-linear-gradient(90deg,${T.alt}60 0 6px,transparent 6px 12px)`}}/></div>}
  </div>);
});

export default Easel;